### ISSUE TITLE
SA1600 reports false positive

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1050]
Hi,

when I use the StyleCop.Analyzers (1.0.0-beta001), I get a false SA1600 violation on following code:

            /// <summary>
            /// Gets or sets some sample text.
            /// </summary>
            /// <value>
            /// A <see cref="string"/> that returns a sample text.
            /// </value>
            public string SampleText { get; set; }

**Comment by sharwell** [comment]
*Interesting.* Based on your report of #1048, I'm guessing this is not a false positive. It sounds like you disabled XML documentation comments for the project. If that is the case, then the warning is arguably correct. What do you think?

**Comment by RalfKoban** [comment]
Hi,
Yes, the XML documentation comments were disabled for that particular project. After enabling them everything was fine. Thanks.

However, I never would have come to that conclusion by myself, so maybe some hints would be really helpful here because the XML documentation itself was completely correct, it was only that the Output XML documentation file checkbox was not checked on the project's Build tab.

**Comment by sharwell** [comment]
Thanks for the feedback. I added a new rule proposal in #1053 which aims to avoid this usability problem in the future. I encourage you to provide feedback and/or any suggestions you may have in that issue. For now I'm closing *this* issue with the **invalid** label because the SA1600 diagnostic is behaving properly according to the information provided by the compiler.
