### ISSUE TITLE
SA1005 Reported for all XML documentation lines

### ISSUE THREAD

**Issue by jcasale** [DotNetAnalyzers/StyleCopAnalyzers#1080]
Looking through the issue tracker doesn't reveal this, however for every XML comment "///" I am getting an SA1005 error. This is a vs2015 community edition install. I'd be happy to provide code/logs if required.

**Comment by sharwell** [comment]
Hi @jcasale and welcome to the project :smile: 

This was previously reported as #1012 and #1048. It is caused by a misconfiguration of the project. Since it was a common problem and not easy to understand, we create a new diagnostic specifically to catch this. You can read about it in [SA1652](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1652.md).

In the recent Beta 2 release, the bugs resulting from disabling documentation comments should now be replaced by warning SA1652. If you are running Beta 2 (or later) and still seeing this issue, please feel free to reopen it. :smile:
