### ISSUE TITLE
QUESTION: Can I have a solution level ruleset

### ISSUE THREAD

**Issue by gep13** [DotNetAnalyzers/StyleCopAnalyzers#1081]
I have just started using the StyleCop Analyzers, and I wanted to know if it is possible to have a solution level ruleset file, rather than one per project?

**Comment by sharwell** [comment]
You sure can. :smile: We actually use one for this project; check out pull request #461. :+1:

**Comment by gep13** [comment]
Nice one, thank you very much, I will get that set up this way as well. Thanks!

**Comment by xperiandri** [comment]
So I just need to put a file 1 level up and reference it from all the projects I want, don't I?

**Comment by vweijsters** [comment]
@xperiandri Yes, that would work

**Comment by julealgon** [comment]
How does one extract the initial ruleset containing all StyleCop rules though? I've been trying to get that to work to no avail: all rules are using standard settings right after I install the nuget package.

**Comment by sharwell** [comment]
@julealgon I don't have a ruleset containing all the StyleCop rules. Normally I take an approach where I only disable rules that were reporting problems. However, this commit should be complete or close to complete:

dotnet/roslyn@2719da11b557ab786ab21177719c193a7dbfe7a9

**Comment by julealgon** [comment]
> @julealgon I don't have a ruleset containing all the StyleCop rules. Normally I take an approach where I only disable rules that were reporting problems. However, this commit should be complete or close to complete:
>
> dotnet/roslyn@2719da1

Thanks @sharwell , I'll look into that.

I just went and manually set all rules to `None` in the SolutionExplorer, which in turn added the entries for each rule into my ruleset file. Quite cumbersome... I wonder if we couldn't think about a way to provide this.

In our case here, I wanted to start with no rules enabled for an entire solution, since it is a big existing project, and then slowly migrate by enabling rules one-by-one and fixing the problems. I feel like this might be a common enough scenario to consider having the full ruleset somewhere, or have a way to generate it.
