### ISSUE TITLE
SA1642 - allow localized standard text

### ISSUE THREAD

**Issue by IngbertPalm** [DotNetAnalyzers/StyleCopAnalyzers#1143]
Please allow localized standard text for this rule.

**Comment by sharwell** [comment]
@AArnott any idea how something like this would even work? Where does your team store the non-English version of the API documentation?

**Comment by AArnott** [comment]
At Microsoft the non-English docs are authored and stored entirely independently of the source code. Basically a localization team takes our compiler-produced .xml file and translates it directly to MSDN documentation. I've never seen an xml doc file that had been translated into another xml doc comment file. 
But our loc process is our own, and other companies, perhaps those working natively in a non-English language (or with customers that are not natively english) could certainly have an interest in documenting in source code in some other language as well. 

To satisfy this, our StyleCop rule would need to compare the text it finds against a string resource rather than a string literal. Then we'd need to provide the translation for that string resource for each supported language. We could get the string from MSDN itself simply by looking at the translated version of the page and see what the template text is for that member type. 
As for how the analyzer would know which language to fill in, perhaps we'd have to simply rely on the current thread's culture setting, which would tie it to the VS instance's language settings (e.g. tying it perhaps to the Windows user setting).
The really tricky part (I'm just thinking out loud here) would then be to not flag as an error to the user that the text is wrong when verifying later with a different culture active. So we'd have to allow *all* translations of the text, yet produce (in the code fix) the text with the culture that makes sense (either always English or perhaps the local culture).

Possible? yes. But I might wait to see how many others request this before starting work.

**Comment by IngbertPalm** [comment]
Hi, I came back to this enhancement..

Is the stylecop.json file not a solution for this? 
If the default texts of all localizable rules can be overridden by the json file, this would be a solution for me.

Would this be feasible?

**Comment by AArnott** [comment]
That sounds reasonable, as that would lock in a particular locale.

**Comment by fubar-coder** [comment]
I'd be fine with the ```stylecop.json``` support as this provides at least (almost) the same functionality as StyleCop had.

**Comment by patricksadowski** [comment]
Alternative proposal: The analyzer could use the language specified by the `NeutralResourcesLanguageAttribute`.

**Comment by GregReddick** [comment]
I think the NeutralResourcesLanguageAttribute should indicate the language of the writers of the code including the comments inside the code. How common is it that there ever a time where the resources in the code (non-satellite assembly) and the languages of the comments aren't the same language?

**Comment by patricksadowski** [comment]
The summary of the attribute is: "_Informs the resource manager of an app's default culture._"

I think it's common to write code in english. The language of summaries, comments and resources should be the main language of the developer team to simplify the software development process. This set of texts can be translated by a translation agency.

How has StyleCop solved the problem?

**Comment by fubar-coder** [comment]
Stylecop solved the problem with a configuration setting in its configuration file.

**Comment by Dennis-Petrov** [comment]
> which would tie it to the VS instance's language settings

I don't think, that it's a good idea.  
The better place will be `stylecop.json`. We have English UI both in Windows and Visual Studio (this is corporate policy), and it's convenient to have XML docs in Russian. Moreover, there are such possible cases:

- source code could be accessed by Russian-speaking developer, which is located outside Russia (that is, OS location setting is not the way to go);
- source code with English XML docs could be included in project.

IMO, the best way to achieve localization in StyleCop is a set of allowed cultures and appropriate resource assemblies.

**Comment by yodasad** [comment]
Moreover this issue is the only problem that stops us from using StyleCopAnalyzers. We have a lot of comments being written in our native language, so now we have tons of rules violations (and of course we don't want to disable these rules).

**Comment by dfyx** [comment]
Same here. Our team decided to document our code in our native language (mainly because we're dealing with a lot of legal terms that are incredibly hard to translate).

With the old StyleCop we could just set `<StringProperty Name="Culture">de-DE</StringProperty>` in `Settings.StyleCop`.

**Comment by dfyx** [comment]
The old StyleCop/StyleCop project stores the localized versions in some `,resx` files located at [Project/Src/AddIns/CSharp/Analyzers](https://github.com/StyleCop/StyleCop/tree/master/Project/Src/AddIns/CSharp/Analyzers). I guess you can use them as a reference. Currently they appear to support en-US (default), en-GB, de-DE, fr-FR, pl-PL, pt-BR and ru-RU.

**Comment by dfyx** [comment]
Looking at the code, this addition looks pretty simple. `PropertySummaryDocumentationAnalyzer` already gets the expected strings from a resource file and it would be trivial to convert all the other classes.

The only thing left to do is to pass a settings object to those classes, add a `DocumentationLocale` to the settings and access the resourceFile via [ResourceManager.GetString(name, culture)](https://msdn.microsoft.com/en-us/library/bsb0cfet(v=vs.110).aspx).

**Comment by dfyx** [comment]
Ongoing progress at https://github.com/dfyx/StyleCopAnalyzers/tree/implement-1143

**Comment by dfyx** [comment]
Aaaaand done!

**Comment by dfyx** [comment]
Alright, I merged your improvements.
