### ISSUE TITLE
Disable SA1412 by default until we can work out the usability problems

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1240]
SA1412 "works", but it currently has several usability problems that people need to be aware of before applying it to their projects. We should set the diagnostic as `DisabledByDefault` until we figure out how to address the other issues.

Current issues related to this:

* #1168 
* #1169 
* #1239

**Comment by Noryoko** [comment]
Grabbing.

**Comment by julealgon** [comment]
@sharwell , I found this issue because I intended to ask a question regarding why this specific analyzer rule was turned off by default. While I'm glad I found it and thus won't need to create my question issue, I'd propose that the _reason_ why the rule has been disabled by default be made explicit in the documentation page for the rule, or at least in the `dotnetanalyzers.github.io` page.

All it says there today is this:
> 📝 This rule is new for StyleCop Analyzers, and was not present in StyleCop Classic.

I believe exposing the reason as to why it is disabled by default would help other folks looking for the information like I was.

This of course goes for any other "disabled-by-default" rule.
