### ISSUE TITLE
Default Enforcement of SA1121 Should be dropped.

### ISSUE THREAD

**Issue by DarkBond** [DotNetAnalyzers/StyleCopAnalyzers#1248]
The argument for using 'int' instead of 'Int32' is becoming more and more irrelevant as time goes by. Portability just isn't an issue and even if it was, nothing is more portable than Int32; it's the same size on every machine. I deal with Interop all the time and it is much cleaner to see the datatypes up front rather than relying on some hidden mapping of aliases to datatypes. SA1121 is irrelevant.

'int' is not an essential part of the C# language. You could remove 'int', 'float', 'bool' and not diminish the language one iota. They may be reserved words, but they are not essential keywords and shouldn't have the same weight as 'for', 'while' and 'try'. Built-In Alias Types are superfluous.

There is no difference between System.DateTime and System.Double, so why does StyleCop treat them differently? They come from the same library, they are both 'primitive' datatypes, so why does SA1121 bark if I have a 'System.Double' in my code but not if I have a 'System.DateTime'? SA1121 is arbitrary.

The reason that 'int', 'double' and 'bool' aliases were included in the language was to make adoption go more smoothly for the older 'C' and 'C++' coders. The reason there is no 'datetime' keyword is because there is no analog in the older languages. These aliases are nothing more than built-in 'using' statements and reduce to 'using int = System.Int32'. The original purpose of these aliases was not to make the language better, but to make marketing easier.  We no longer need to market to that demographic.

15 years after the introduction of C#, the only remaining purpose of the built-in aliases is to obfuscate the language.

**Comment by Maxwe11** [comment]
All rules should be enabled by default. If don't using something you can disable in your personal ruleset file.

**Comment by sharwell** [comment]
The primary thing offered by SA1121 is uniformity in referencing a named code element. An alternative rule offering the same benefit would have been to always reference built-in types by their metadata name (e.g. report a warning on `int` and fix it to `Int32`).

In the case of SA1121, this is a rule we inherited from StyleCop "classic". Changing it at this point to the alternative described here would be problematic; it would require existing users make substantial changes to their code to comply with the new rule. However, if you want to use the alternative form you could certainly propose an SX1121 "alternative rule" which enforced such a standard.

If you do not wish to enforce this rule, you can create a **.ruleset** file which disables the rule, and then apply it to each project in the solution. We use this strategy even in this project to disable some rules (and also to set other rules to report errors instead of warnings). More information on these files is linked in the readme.

> All rules should be enabled by default. If don't using something you can disable in your personal ruleset file.

Some rules are disabled by default. We have a column to identify them on the status page.

**Comment by DarkBond** [comment]
I agree that you need uniformity in referencing code elements.  I am arguing that an 'alias' is not a code element: in this case it's an obsolete macro.
I certainly understand the backward compatibility issue.  However, if a compromise was made 15 years ago by the marketing guys, do we really want to immortalize that mistake with rule in StyleCop for the remaining life of this language?
Read the description of SA1121.  Unlike every other rule in the analyzer, there is no explanation of why this rule is needed.

**Comment by sharwell** [comment]
Aside from its status as a long-standing StyleCop rule, I see the following advantages:

* In all cases, the keyword is at most the same number of characters long as the metadata name for the type
* There is no need to rely on a `using System;` declaration, and no risk of naming collisions (`System.Int32` is not enough to guarantee the reference is correct in all cases, but `int` is)
* This rule is consistent with SA1125 in that in prefers language-specific features over the longer form used by the VM

**Comment by DarkBond** [comment]
I agree that it's status as a longstanding rule is the best argument, but being an engineer I bristle at the thought of a mistake becoming dogma.  As to your other points:

1. The length of the type doesn't matter when you have autocomplete.  It's probably been 10 years since I actually completed typing a full type name - this is a wash.
2. I have, on average, between 10 and 15 'using' statements in any given module.  The opportunity to remove one (e.g. 'System') should not a consideration for productivity.  Again, most of the time I just type the name and then use the lightning-bold/light bulb to add the 'using' statement. - a wash.
3. I can't speak for SA1125 because, again, there's no reason given for it.  C# is a language of metadata and that's what makes it special.  You can't separate C# from the VM.  That is, there are no 'language specific' data types in C#.  C++, on the other hand, is a language of built-in types that are distinct from user generated objects.  The introduction of these aliases into the language creates an undesirable bifurcation: why does StyleCop flag 'System.Int32' and not 'System.DateTime'?

**Comment by oatkins** [comment]
> SA1121 is arbitrary.

Most of the StyleCop rules are arbitrary; it's the very nature of the program, since most rules relate to formatting that has no effect whatsoever on the generated IL.

I personally prefer the use of the built-in aliases, but that's a immaterial. StyleCop enforces consistency, and in so doing, makes an arbitrary determination as to what form is preferred. Historically, the project made little concession to preference, in that there was little opportunity for customization. That is rectified here, to some extent, by the alternative SX???? rules.

> Built-In Alias Types are superfluous.

A lot of the C# language is "superfluous": `foreach`, `using`, linq query syntax, iterator methods, etc., etc. Were all those features "mistakes"?

**Comment by sharwell** [comment]
I'm moving this to **wontfix**, but a proposal for an SX1121 alternative rule should be fairly straightforward to define. See #837 for an example.

**Comment by DarkBond** [comment]
Thank you for considering my arguments.

**Comment by DarkBond** [comment]
> A lot of the C# language is "superfluous": foreach, using, linq query syntax, iterator methods, etc., etc. Were all those features "mistakes"?
The main difference here is if I wanted to use the original form for a 'lock' statement, or use the native linq methods instead of the syntactic sugar (something I see often), then I don't generate a warning from StyleCop.
And, *no*, they were not mistakes because the keywords in your example made the language better.  I recognize the need for aliases 15 years ago when acceptance was a criteria.  The only argument you can give now for `int`, `bool`, `float` as reserved keywords is that it provides comfort for people who's first language was 'C' or 'C++' as is evident by their arbitrary application.
