### ISSUE TITLE
"SA1600 Elements must be documented" not working

### ISSUE THREAD

**Issue by chrfin** [DotNetAnalyzers/StyleCopAnalyzers#1282]
It seems that the rule [SA1600](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1600.md) is not working (anymore?), but the [status page](http://stylecop.pdelvo.com/?category=StyleCop.CSharp.DocumentationRules) tells it has an implementation.

I tested this with an empty WPF project and `beta008`. The `MainWindow` constructor has no documentation, but no warning about SA1600 is given.

**Comment by sharwell** [comment]
:question: Is `MainWindow` a partial class? If so, the applicable warning would be SA1601 instead of SA1600.

**Comment by sharwell** [comment]
I found the issue. SA1600 is automatically disabled any time SA1652 is reported. This is the case for new WPF projects.

You need to enable documentation comment diagnostics for your project as described in [SA1652](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1652.md) before any of the related diagnostics will be active.

**Comment by chrfin** [comment]
Thanks - problem solved. Wasn't aware of that constraint as it was not present in the "old StyleCop".
As a side note: I had to disable CS1591 (which is basically the same as SA1600), because that one complained about missing XML documentation in the auto-generated `Settings.Designer.cs` files. But as SA1600 checks that "correctly" thats fine IMO (and avoids "double warnings" form both rules).

**Comment by sharwell** [comment]
Glad it's fixed :+1:

Please feel free to stick around and comment on feature proposals and consider filing bugs/enhancement request if you run into trouble. :smile: 

> Wasn't aware of that constraint as it was not present in the "old StyleCop".

It's a limitation imposed by Roslyn that we unfortunately have little control over aside from reporting it as its own warning. We actually introduced SA1652 because of the number of bug reports that were filed related to this.

**Comment by chrfin** [comment]
I actually disabled SA1652 because I thought it was not necessary, as I did not read the description :stuck_out_tongue_closed_eyes:. May add a little hint directly to that warning:
`Enable XML documentation output - required by SA16xx` or similar?

Thanks again for your feedback and great work!

**Comment by Schwenkner** [comment]
I was today running into the same problem. But all the hints given here didn't help.
First, SA1652 went to SA0001, I've read. None of the changes (I tried all possibles) didn't help.
Then I installed StyleCop 1.1.0-beta006 and the problem was gone. I could force SA1600 to be an error when alanyzing in VS2017. There was no need do change SA0001/1652.

But then I pushed that project to CI. And there SA1600 was not reported as error, neither as warning. This I've again tried to change SA0001, also without success.

How can I force SA1600 to be an error on msbuild? I also tried the nuget package StyleCop.msbuild, unfortunately with the same result. For this package there is no beta which (I thought) could have fixed the issue.
