### ISSUE TITLE
Resharper support

### ISSUE THREAD

**Issue by ioancrisan** [DotNetAnalyzers/StyleCopAnalyzers#1346]
Hi all,
sorry I add this nice to have feature here, but I didn't see it requested anywhere. Do you guys plan to make the two tools play nice with one another? Are any plans whatsoever in this direction? I follow the project from some time, and I plan to use it as soon it hits the v1 level. I do use however Resharper as my primary dev tool and my only concern is to make both of them compatible. The current Stylecop plugin for Resharper works pretty well, even though in beta, with minor issues that I can ignore. I would be grateful if you could share your plans in this direction.

Btw, your work is awesome, congrats!

**Comment by sharwell** [comment]
I don't use ReSharper myself, but I have a coworker that uses it daily and hasn't had problems so far using it with StyleCop Analyzers.

Note that ReSharper by default disables the preview which appears in the light bulb menu in Visual Studio 2015, which means it also disables the ability to fix all instances of a violation in a document, project, or solution. For the best experience, you may need to disable ReSharper's "merged light bulb" feature (I think this is what it was called).

**Comment by ioancrisan** [comment]
What I meant was that Resharper and Stylecop have in some cases different standards, for example like using or not using the _ (underscore) in private fields' names. I don't know exactly which component does it, but either resharper or stylecop addin warns that there are differences in these standards/settings and makes resharper use the stylecop standards. If this will not be automated in the first phase, could I at least see which are these differences, and maybe manually adjust them?

**Comment by sharwell** [comment]
There are currently no plans to do this. StyleCop Analyzers and its code fixes operate independently of the settings a user has chosen within the IDE. If a Roslyn API to configure formatting settings is available in the future, it would probably make sense for this project to integrate with it, but manipulation of settings using IDE- or extension-specific APIs is likely beyond the scope of this project.

**Comment by ioancrisan** [comment]
Thanks for your reply!

**Comment by geoarion** [comment]
Note to any future visitors to this page: the closest way I've found so far to make the Resharper and StyleCop Analyzers to play nice together is to have Resharper configured with the old non-Roslyn based stylecop tool, so that you have a a "StyleCop" profile when using code cleanup in Resharper.

After that, you can use "Cleanup Code" w/ the "StyleCop" profile in Resharper which generally auto-fixes a lot of the issues that StyleCop (the old one) would report. However, at this point, this is likely to introduce a lot of white spaces at the end of certain lines (e.g.: after every line in a multi-line method call with named parameters) that trigger warnings with some of the new rules in StyleCop analyzers and other minor issues. 
Immediately after that, a Visual Studio "Format Document" is enough to fix the remaining issues (as I believe it now uses the Roslyn code analyzers in some way for the code fixes).
(Ctrl + E,C   ;  Ctrl E, D).

If anyone has found a cleaner way, please let me know :).
