### ISSUE TITLE
Implement SA1129 (DoNotUseDefaultValueTypeConstructor)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1482]
**Category:** Readability
**Title:** Use `default(T)` to create default value type instances
**Description:** A default instance of a value type `T` may be obtained by either `default(T)` or `new T()`. In these scenarios, the `default(T)` syntax should be used.

**Rationale:** This is especially applicable for code using `ImmutableArray<T>` (a value type). Code which formerly used `List<T>` or `T[]` (both reference types) need to be very careful not to mistake `new ImmutableArray<T>()` for the same behavior. This syntax results in a default `ImmutableArray<T>` instance, whose behavior more closely resembles `null` than any non-null instance (especially in regards to exceptions being thrown). Similar behavior can be seen for `Nullable<T>`.

:memo: This proposal only refers to the distinction between `default(T)` and `new T()`. Other default values, including `CancellationToken.None`, `0`, `0.0f`, `IntPtr.Zero`, and `RegexOptions.None`, would *not* produce a warning.

:memo: This proposal was inspired by code observed in [dotnet/Roslyn#5180 (comment)](https://github.com/dotnet/roslyn/pull/5180#discussion_r39443514).

**Comment by vweijsters** [comment]
:+1:

**Comment by Maxwe11** [comment]
:+1:

**Comment by otac0n** [comment]
I'm :-1:, because the advice boils down to "never use parameterless constructors for structs" which, to me, is quite dubious.

Basically, if `default(MyStruct)` and `new MyStruct()` behave differently, it would stand to reason that the author of the struct did this intentionally.  That is to say, there was a case in the author's mind that lead them to intentionally create a parameterless constructor that behaves differently than `default(T)`.  

So, in the *general* case, this seems wrong to me.

This *does* seems like very good advice for the Immutable Array case, so I think it should probably be added to Code Analysis.

**Comment by pdelvo** [comment]
A struct can't have a parameterless constructor. So default(MyStruct) and new MyStruct() behave the same.

**Comment by otac0n** [comment]
@pdelvo Fair point.  :+1:

**Comment by sharwell** [comment]
@otac0n Does your :+1: mean you just retracted the :-1: vote, or are you adding a :+1: in favor of the proposal?

**Comment by Tinister** [comment]
public struct Struct
    {
        public int Property { get; }
    
        public Struct(int value = 1)
        {
            this.Property = value;
        }
    }
    
    public static void Main(string[] args)
    {
        Struct s = new Struct();
    }

Wouldn't changing the body of `Main` to `Struct s = default(Struct);` completely change the behavior?

**Comment by sharwell** [comment]
@Tinister No, it wouldn't. In that example you are not calling the user-defined constructor. The compiled bytecode contains an [`initobj`](https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.initobj.aspx) instruction for this code. If anything, IMO the examples shown by you and @otac0n are prime examples of the value of this rule; the syntax `new T()` when `T` is a value type is easily misleading under a variety of situations.

**Comment by Tinister** [comment]
Oh jeez, I should have tried that before opening my mouth.  Now I'm left wondering why creating a struct constructor with all optional params isn't a warning.

Otherwise, I really like this proposal.

Early previews of C# 6 let you create default constructors for structs, do you know if that's been shelved indefinitely?

**Comment by otac0n** [comment]
@sharwell Uh, both?

**Comment by sharwell** [comment]
> Early previews of C# 6 let you create default constructors for structs, do you know if that idea has been shelved indefinitely?

The feature was reverted due to unforeseen problems with no clear path to a solution. As a result, I don't expect it to return any time soon.
