### ISSUE TITLE
CI reports "success" when test failed

### ISSUE THREAD

**Issue by Maxwe11** [DotNetAnalyzers/StyleCopAnalyzers#1560]
https://ci.appveyor.com/project/sharwell/stylecopanalyzers/build/1.0.1897

**Comment by sharwell** [comment]
I was hoping to avoid two separate phases for tests and code coverage, especially since the code coverage phase was reporting a duplicate set of test results. Looks like that won't be possible though. :worried: 

Any idea on how we can get the code coverage results to not appear on the Tests tab of AppVeyor, since they duplicate information already put there by a previous test run?
