### ISSUE TITLE
How to ignore files from StyleCop?

### ISSUE THREAD

**Issue by mreu** [DotNetAnalyzers/StyleCopAnalyzers#1573]
We are using a custom tool (protobuf-net) that generates .cs files. Unfortunately these files are not compatible with our StyleCop rules. With the old StyleCop we could mark them as not to be checked. How can I do this with StyleCop Analyzers?

**Comment by sharwell** [comment]
Based on the [source code](https://github.com/mgravell/protobuf-net/blob/master/ProtoGen/csharp.xslt#L38-L45) for this generator, it looks like the generated files would already be excluded from analysis. You can see an example of this in mgravell/protobuf-net@0f7b375981299cb6f9fff6db0c65c85a97d0ff49.

Can you provide a bit more information to help narrow this down? If your project is open source, a link would be amazing! Otherwise:

1. What does the comment at the top of one of your generated files look like?
2. What is the name of one of your input file and the associated output file with warnings?
3. What is one StyleCop warning you are seeing reported in this file?

**Comment by mreu** [comment]
Sorry for the delay.
You are right, the generated files are not checked by StyleCopAnalyzers. I saw a lot of CS warnings and thought they came from StyleCopAnalyzers.

But back to my question: Is it possible to mark a file not to be checked as in the old StyleCop? If not now, is it planned?

**Comment by sharwell** [comment]
There are no concrete plans at this time, but issue #1430 is open for further discussion to see if any changes need to be made.
