### ISSUE TITLE
Proposal: SA1118 (ParameterMustNotSpanMultipleLines) exception for method invocations

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1597]
Currently SA1118 documents two exceptions: the first parameter, and any parameter which is an anonymous method.

> To prevent method calls from becoming excessively complicated and unreadable, only the first parameter to a method or indexer call is allowed to span across multiple lines. The exception is an anonymous method passed as a parameter, which is always allowed to span multiple lines.

To improve support for constructing types like `XElement`, I propose adding an additional exception to this rule for method invocations, indexer expressions, and object initializer expressions. Note that the arguments passed to the method, indexer, or constructor must still adhere to this rule.

:memo: This exception would provide us with an easily-documented resolution to #1596.

**Comment by vweijsters** [comment]
:+1:

**Comment by grokys** [comment]
:+1: PLEASE!!!

**Comment by sharwell** [comment]
It appears this exception was implemented but not documented in StyleCop Classic.

**Comment by martincostello** [comment]
In addition to ```XElement```, another use case is Moq's ```It.Is<T>(Expression<Func<T, bool>> match)``` method used for setting up instances of ```Mock<T>```.

For example:

```
var mock = new Mock<MyClass>();

mock.Setup(
     (p) => p.MyMethod(
         "MyValue",
         It.Is<Foo>(
             (r) => r.Bar == "Buzz" &&
                    r.Frob == 2)))
    .Returns(() => new FooBar());
```

I've got a few occurrences in code where the expression tree is quite complex, so is split over multiple lines. In StyleCop classic this didn't raise a warning, but does using the new analysers.

Splitting it into a single line creates a ridiculously long line, and pulling the ```It.Is<T>()``` call out into a variable causes the test to no longer work, presumably because of something to do with the way Moq handles expression trees.
