### ISSUE TITLE
SA1129 proposes significant code change rather than style

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#1666]
The SA1129 rule proposes that this syntax be used:

     default(int)

instead of

    new int();

For many structs this is fine, since their default constructor is empty. However the CLI specification does not require that a struct's default constructor be empty. And in fact C++/CLI allows for non-empty implementations, and C# 6 _almost_ allowed it, and a subsequent version of C# certainly may. Therefore, these two forms are _not equivalent_ and therefore this is not mere style.

I'd like to open a discussion here to discuss disabling this rule by default.

**Comment by sharwell** [comment]
According to ECMA 334 §11.1.2, the expressions `new T()` and `default(T)` are equivalent for any value type `T`. While C++/CLI may be able to express a parameterless constructor with differing behavior, and compliant C# compiler is not required to call this constructor (but also does not disallow it). If anything, the explicit use of `default(T)` ensures that the compiled code behaves the same way regardless of the compiler which is used.

> ...C# 6 almost allowed it, and a subsequent version of C# certainly may.

This was mentioned in #1482. The outcome of the work on this front in C# 6 was the feature would not work as expected and the outcome appears to have satisfied the desires of former proponents of the language feature. I do not expect it to return.

> I'd like to open a discussion here to discuss disabling this rule by default.

I believe the rule should remain enabled by default for the reasons discussed in #1482. On multiple occasions I have seen code like `new ImmutableArray<int>()` which appears correct in source code and reviews but does not behave *at all* like the author intended. SA1129 makes it harder for bugs to appear due to misinterpretation of values during code reviews.

**Comment by AArnott** [comment]
> According to ECMA-334 §11.1.2, the expressions new T() and default(T) are equivalent for any value type T.

I assume that you merely omitted the type constraint on `T` in your paraphrase, as for this statement to be true, `T : struct` at least, since it certainly isn't true for `T : class`. 

I am surprised to hear that given that the C# team was considering a design that sounds like it would contradict this. But in light of that, I accept your reasoning.

**Comment by sharwell** [comment]
@AArnott I meant to imply the constraint by stating "value type `T`", as opposed to a reference type.

**Comment by AArnott** [comment]
Ah yes, of course. I should have caught that.

**Comment by sharwell** [comment]
Have we addressed your concerns, or are you still in favor of changing the rule to be disabled by default?

**Comment by AArnott** [comment]
I'm satisfied.
