### ISSUE TITLE
Manual steps for configuring stylecop.json for UWP

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1684]
When working with a Universal Windows Application, or more generally any project that uses **project.json** instead of the old project format, the custom targets file added in #1581 does not work. In these cases, the workaround which was previously documented in Configuration.md is still required. The documentation which was removed in #1636 should be added again, and start with a note that it is only required for cases where **project.json** is in use.

Thanks to @bexxx, @AArnott, and @pdelvo for tracking this down.

**Comment by AArnott** [comment]
After the fix for https://github.com/NuGet/Home/issues/1461 is released, this issue should automatically go away. In the meantime, you can workaround by moving the .targets file into a broadly applying PCL TxM folder like [this](https://github.com/AArnott/Nerdbank.GitVersioning/tree/master/src/Nerdbank.GitVersioning.NuGet/build/portable-net%2Bwin%2Bwpa%2Bwp%2Bsl%2Bnet-cf%2Bnetmf%2BMonoAndroid%2BMonoTouch%2BXamarin.iOS).

**Comment by sharwell** [comment]
This was fixed in #1790.
