### ISSUE TITLE
SA1650: ElementDocumentationMustBeSpelledCorrectly

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#170]

**Comment by sharwell** [comment]
Marking **wontfix** based on #1057.

**Comment by marspion** [comment]
Hello,

i didn't want to create new topic because im not sure it is issue with StyleCop or with my PC configuration.
I have a problem with SA1650 rule. I reinstalled system on my PC (before reinstallation everything worked properly) and after that my StyleCop don't check documentation headers by correctly check (Polish language). I tried to reinstall StyleCop, copy settings from other programmers but it didn't help.

Do you know anything about this problem?

**Comment by sharwell** [comment]
@marspion You should create a new issue or no one will see the question (issues mostly disappear after they are closed).
