### ISSUE TITLE
Needs to support .NET CoreClr coding style

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1722]
I would like to use these analyzers but our team has adopted the coding style required by the .NET CoreClr that contributors need to follow:

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

It would be nice if the rules could support the above coding style guidelines.  For instance, how can I enforce that private/internal instance fields are prefixed with `_` and static private/internal fields are prefixed with `s_`.

While I understand that StyleCop tried to proffer a universal C# coding style as embodied by its rule, I've frankly never liked that "style".  Seems like the tool should be more about enforcement of whatever style a team decides to use.  However if you feel strongly about StyleCop steering folks in the direction of a common style, I think it should be the one the MS team has specified for CoreClr.

**Comment by vweijsters** [comment]
Thanks for your feedback. It is a goal of this project to make sure that (with some configuration) the mentioned coding style is supported. Most of it should be supported already, if there are specific problems please create an issue for each problem that you encounter to make sure that we can easily address and track it. 

Several of our optional rules already provide functionality towards verifying the CoreClr coding style guide. For further information please have a look at [SX1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1309.md), [SX1309S](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1309s.md), and [SX1101](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1101.md). These rules are disabled by default, as they are not compatible with the original StyleCop implementation. When enabling them, make sure to disable their original counter parts (SA1101 and SA1309), as otherwise conflicts between the analyzers will arise.

One of the key goals of this project is to make sure that StyleCop Analyzers is (as much as possible) compatible with the original StyleCop implementation. Where useful we try to offer additional (alternative) rules to give teams the flexibility to modify the rules to their liking.

**Comment by rkeithhill** [comment]
Thanks for the info - very useful.  BTW I don't think SX1309S follows the CoreClr convention which would be `s_field` for a private static field.   Perhaps we need another rule?
