### ISSUE TITLE
SA1649 (File name must match first type name) for generic types shouldn't require generic specification

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1730]
For the type `Fish<T>`, legacy StyleCop permits either "Fish{T}.cs" *or* "Fish.cs" as the file name.

Our analyzer allows the former, prefers "Fish`1" but does not accept plain old "Fish.cs". I like the legacy behaviour, since I prefer to omit the qualification in the file name unless there is a non-generic version of the type too.

Apologies if this has already been discussed, but I couldn't find evidence of that.

**Comment by sharwell** [comment]
The current implementation should not accept both **Fish{T}.cs** and **Fish`1.cs**. The naming convention should be controlled by the fileNamingConvention configuration option. When using the metadata naming convention, the generic type arity would always be required (the metadata name of `Fish<T>` is <tt>Fish&#x60;1</tt>, not `Fish`). When using the stylecop naming convention, I think we should stick to the behavior of StyleCop Classic.

@vweijsters can you confirm that the behavior of StyleCop Classic deviates from our implementation? This is slightly different from the test we ran in #1710.

For example, what happens if you have the following content in **X.cs**?

```csharp
// <copyright file="X.cs" company="My Company">
//     Custom company copyright tag.
// </copyright>

public class X<T>
{
}
```

**Comment by vweijsters** [comment]
@sharwell For this example SA1649 is not reported. I think we should fix this for the `stylecop` file naming convention.

**Comment by sharwell** [comment]
Agreed, but only for the `stylecop` naming convention. :+1:

**Comment by sharwell** [comment]
Summary of desired behavior for class `Foo<T>` with the `stylecop` naming convention:

* Analyzer: allow **Foo{T}.cs** or **Foo.cs**
* Code fix: always move the class to **Foo{T}.cs**

**Comment by pdelvo** [comment]
grabbed
