### ISSUE TITLE
Reading settings file from the solution

### ISSUE THREAD

**Issue by arashk1368** [DotNetAnalyzers/StyleCopAnalyzers#1732]
Hi,

It would be nice to be able to define the settings in the solution level and use it in the projects. I tried to put stylecop.json file in the solution but, the analyzer is not reading it.

**Comment by vweijsters** [comment]
What you can do is define the `stylecop.json` file in the solution folder and create a link to it from each project. That should work fine. I don't think that an other solution is currently possible, given that analyzers currently cannot access the MSBuild environment at all.

**Comment by arashk1368** [comment]
Yes, that would be possible. However, because you have to include the settings file inside of the csproj file, Visual Studio will have problems. Generally, it has issues when two projects in the same solution reference the same file.

**Comment by wwwlicious** [comment]
For the original stylecop I currently generate project level settings.stylecop files to link to a solution level settings.stylecop file and automate copying this link file to all solution projects (regardless of folder nesting) (where they do not exist) using nuget init.ps1 scripts that run (but only when you open the package explorer). This ensures that even as projects are added and removed over time, the projects always link back to a solution level settings file. It's far more complex than it needs to be.

It would be much easier and more robust IMO to follow the conventions used by linting tools like jshint which use recursive parent lookups for locating settings files. 

Just my two cents

**Comment by sharwell** [comment]
@arashk1368 @wwwlicious Based on a meeting I had this week, it's almost certain that the method of including configuration will change (and be *much* more usable) in an upcoming release of Roslyn (I'm crossing my fingers for 1.2). Prior to that, I don't plan to make any changes based solely on usability (since it would just change again with the Roslyn update).

With Roslyn and our analyzers as portable class libraries, most of the file system APIs are not available, so we don't want to design an approach that requires us to use them (e.g. the jslint approach). That said, it might be possible to update the custom build target to locate and include the stylecop.json file from the solution directory if one doesn't already exist in the project.
