### ISSUE TITLE
Can we start using this for production code?

### ISSUE THREAD

**Issue by RehanSaeed** [DotNetAnalyzers/StyleCopAnalyzers#1815]
How stable/usable is this project now? Can we start using it for our production code? The [list](http://stylecop.pdelvo.com/) of implemented rules seems almost complete now.

**Comment by sharwell** [comment]
The project is quite stable IMO. We've been using it in production since Beta 6.

Note that there is a bug (#1795) in the latest release, so you may see AD0001 messages appearing in Visual Studio (it doesn't affect command line builds). With that fixed along with initial documentation of [known differences](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/documentation/KnownChanges.md) between StyleCop Classic and this project, I'm hoping to see wider adoption starting with Beta 17.

**Comment by RehanSaeed** [comment]
Thanks @sharwell, exactly the answer I was looking for.
