### ISSUE TITLE
SA1028: Memory leak?

### ISSUE THREAD

**Issue by fubar-coder** [DotNetAnalyzers/StyleCopAnalyzers#1877]
We have a situation where VS 2015 Update 1 crashes under the following condition:

- A C# project with >250 classes / files
- 20-30 of them contain trailing whitespace characters
- Apply the code fix on the project

Visual Studio tries to use more than 2.7G memory and therefore crashes with (probably) an OutOfMemory exception.

I didn't notice this problem with other analzers/fixes, but it might still be a VS problem.

**Comment by sharwell** [comment]
Can you confirm that you were actually fixing SA1208? In some cases, multiple diagnostics may be reported on the same line, and it's pretty easy in some cases to fix one that's not obvious. I ask because 1) SA1208 relates to using directives while you mentioned whitespace at the end of lines, and 2) SA1208 should not suffer from the problem described below. Normally trailing whitespace characters are reported by SA1028, but this is not likely the issue because it's one of our fast*est* code fixers (#1374, #1412).

If SA1208 is the culprit, then it's very likely that we have a memory leak. Until we know for sure, I'm going to mark this as a blocking bug for the 1.0 release.

### What to do if SA1208 is really the culprit

This should be a reproducible problem within one or more documents in your project. Step 1 will identify the culprit for us. The steps after Step 1 are only meant to remove information in case your project is closed source and you can't send us the file. When you get to a point where you are comfortable submitting the file, go ahead and stop at whatever step that is. A [gist](https://gist.github.com) would be a good location to submit the file if it's not open source and the behavior is sensitive to whitespace.

1. Use the Fix All in Document operation to identify the document which presents the problem
1. Remove the *body* (everything within `{` and `}`) for each type in the file, but leave all comments in place
1. Change line comments from `// {your text}` to `// comment`
1. Replace the text in block comments with `comment`, but leave `/*`, `*`, and `*/` characters where they are
1. Rename classes and/or namespaces in the file, but leave the structure (including whitespace) intact

### Some history

This behavior is most commonly observed in what we call "slow" code fixes. Specifically, these are code fixes which use [`CustomFixAllProviders.BatchFixer`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/Helpers/CustomFixAllProviders.cs#L29). The [status page](http://stylecop.pdelvo.com) used to display these code fixes using an :hourglass: instead of a :heavy_check_mark:, but this is currently non-functional due to pdelvo/StyleCop.Analyzers.Status#1.

We are faced with a difficult decision. The code fixes tend to work well when applying all changes to a document or a "small" project, which can certainly save people a great deal of time. At the same time, there is no easy way for us to identify these code fixes within a project or detect whether or not the operation will succeed before we actually attempt it.

**Comment by fubar-coder** [comment]
It was indeed SA1028.

**Comment by sharwell** [comment]
@fubar-coder What version are you using? This *should* have been fixed in 1.0.0 Beta 10.

**Comment by fubar-coder** [comment]
1.0.0-rc1

**Comment by sharwell** [comment]
Looks like a bug in Visual Studio 2015 Update 1. StyleCopTester successfully corrected 7272 violations of this rule in 4686ms (Roslyn 1.0) and 4407ms (Roslyn 1.1).

I then replaced every `}` at the end of a line in our project with `}` followed by two spaces (8869 violations). Attempting to fix all violations readily crashed Visual Studio 2015 Update 1. The same operation took 30 seconds to complete successfully in Visual Studio 2015 RTM (20 seconds to bring up the preview, and another 10 for me to click Apply and have it finish applying all changes.

**Comment by fubar-coder** [comment]
Dang. I'll send a frown to the VS team. Sorry for bothering you.

**Comment by sharwell** [comment]
@fubar-coder Don't feel bad for trying to help. Your description was good and I filed a Roslyn bug out of this. :+1:
