### ISSUE TITLE
check that all thrown exceptions are documented

### ISSUE THREAD

**Issue by Trass3r** [DotNetAnalyzers/StyleCopAnalyzers#1950]
https://msdn.microsoft.com/en-us/library/w1htk11d.aspx

**Comment by sharwell** [comment]
This is an extraordinarily difficult rule to get right in practice. Some of the items which can influence this detection are:

* The use of `try`/`catch` blocks - and inside the `catch` blocks you can have `throw` statements.
* `catch` clauses can now use `when` to filter exceptions.
* Code can call other methods which can throw exceptions.
  * Sometimes exceptions which the invocation target can throw are impossible at runtime due to the preconditions of the call itself, meaning the caller could never actually throw that exception.
* Abstract and virtual methods (including interface methods) need to document the exceptions which implementations are allowed to throw, even though the base definition might not throw them at all.

The fate of Red Gate's Exception Hunter product increases my reluctance to include this type of rule. I can't find the announcement anymore, but essentially the problem was exceptions are almost impossible to detect in a meaningful way. You're either going to leave out real exceptions, include unnecessary exceptions, or both.

Even if it were included as an analyzer, I believe the required semantic analysis makes this rule better suited to FxCop than StyleCop.

**Comment by vweijsters** [comment]
I agree with @sharwell, it will be next to impossible to implement this.

**Comment by GregReddick** [comment]
To properly implement this would require a full analysis of the entire call tree to find all the exceptions that are thrown that aren't caught. This would be extraordinarily slow and difficult. I don't even think FxCop is the right place to do this, this is more a tool for some other kind of analyzer that is invoked from a menu item, like the Analyze Assembly Portability analyzer. In some cases there are thrown exceptions in people's code when there really should be an assert that the condition should be impossible. If that is in library code, you don't want to document an exception that cannot really occur. So this needs to have some kind of suppression feature too.

The feel for this is just wrong for StyleCop. I'm not saying that this shouldn't exist, it just shouldn't exist here. :-1:

**Comment by qmfrederik** [comment]
The [Wintellect.Analyzers](https://github.com/Wintellect/Wintellect.Analyzers) have a [WINTELLECT010 Exception XML document tag is missing](http://code.wintellect.com/Wintellect.Analyzers/WebPages/Wintellect010-ExceptionDocumentationMissing.html) rule which forces you to document any exceptions your own code throws.

Seems like a pragmatic approach for those willing to enforce such a rule.
