### ISSUE TITLE
Ordering rules tooltips are hidden by ReSharper

### ISSUE THREAD

**Issue by lflender** [DotNetAnalyzers/StyleCopAnalyzers#1965]
![image](https://cloud.githubusercontent.com/assets/16304182/11844333/95d003ca-a40e-11e5-9488-97e6dae4fde1.png)

As shown in the screenshot, when ReSharper is activated, we can only access the suggestion text in the Error & Warnings window, which is very annoying.

I told them too about this issue: http://resharper-support.jetbrains.com/hc/requests/26620

Thanks for help

**Comment by sharwell** [comment]
This is a ReSharper bug. As you noticed, the text is properly reported to Visual Studio. Since ReSharper overrides the Visual Studio IntelliSense and presentation layer, there is nothing we can do if they choose to ignore the standard API by which we report these tooltips.

I always recommend uninstalling ReSharper. You will get a much better performing and overall cleaner development experience.

**Comment by lflender** [comment]
It's what I thought, thank you very much for your fast answer!
