### ISSUE TITLE
Constants and SA1202 rule.

### ISSUE THREAD

**Issue by NikGovorov** [DotNetAnalyzers/StyleCopAnalyzers#1982]
Hi @sharwell,

Is it expected that SA1202 is applied to constants?

The following example throws SA1202:

```C#
 public class Test
 {
     private const int constant = 1;

     public static readonly int Field = 1;
 }
```

Thanks.

**Comment by NikGovorov** [comment]
Same for ```static```.

**Comment by sharwell** [comment]
Yes, both of these are expected. The default ordering checks were chosen to match StyleCop Classic. See the [Element Order section of **Configuration.md**](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#element-order) for more information about the ordering and how to change it. It sounds like you are interested in changing the order to match the Constants First example there.

:memo: There is no way to change the order so that `static readonly` fields are evaluated with the precedence of constants without also affecting the order in which `static` methods, properties, and events are evaluated.

**Comment by NikGovorov** [comment]
Thanks @sharwell.
