### ISSUE TITLE
Suppression via pragma vs SuppressMessageAttribute

### ISSUE THREAD

**Issue by felickz** [DotNetAnalyzers/StyleCopAnalyzers#2080]
Any reason why some rules are documented & suggested fixes coded to be  suppressed via compiler pragmas and some are with [SuppressMessage("StyleCop.CSharp.MaintainabilityRules" 

Ex: 
[SA1313 - pragma only](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1313.md)
[SA1210 - both ways](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1210.md)

With 1313, Roslyn code fix will only suggest  inline the pragma, BUT if you choose to fix in suppression file it will add the SuppressMessage attribute.

**Comment by sharwell** [comment]
For almost all violations, both ways work fine. Some of the documentation files were migrated from StyleCop Classic and we just haven't had the chance to update all the old documentation to include examples using the new form.

For new rules, we tend to prefer documenting only `#pragma` since it's easier to understand and control exactly which lines are affected by the directive.

**Comment by weitzhandler** [comment]
I'm now trying to suppress CS8620.

Pragma works fine, but when I decorate the method with 

```c#
[SuppressMessage("Compiler", "CS8620")]
```

The message still appears.

![image](https://user-images.githubusercontent.com/2716316/89750442-b0104680-dad4-11ea-8d6c-b3b243e26eb1.png)

**Comment by sharwell** [comment]
CS8620 is a compiler warning. Compiler warnings do not support the SuppressMessage attribute.
