### ISSUE TITLE
SA1003 and SA1009 must not be triggered by cast operator

### ISSUE THREAD

**Issue by xperiandri** [DotNetAnalyzers/StyleCopAnalyzers#2151]
Placing whitespace after cast operator must not trigger SA1003 and SA1009

**Comment by sharwell** [comment]
I read this as the following. Can you confirm that I understood correctly?

> Currently, a space appearing after a cast results in both SA1003 and SA1009 being reported. I expected that only one violation should be reported for any single violation.

**Comment by xperiandri** [comment]
Yes, both are reported.
I don't want that any be reported.
I want the style where a cast operator must be followed by space.

**Comment by sharwell** [comment]
Oh, that is a very different topic. Currently StyleCop does not support the requested style. You can implicitly *allow* a space after a cast (by disabling SA1003 and SA1009 altogether), but there is no way to *require* it.

I would recommend creating a proposal issue suggesting the addition of a configuration option for the behavior of a space after a cast. If accepted, it could then be implemented and appear in a future release. I'm going to close the current issue as **wontfix** since, with the [exception of line endings in SA1003](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/KnownChanges.md#sa1003), the behavior matches StyleCop Classic for the style which is currently supported.

**Comment by xperiandri** [comment]
Where to create it? Here but separate issue?

**Comment by monoblaine** [comment]
@xperiandri I had the same issue: I wanted to have StyleCop fix spacing issues but I also wanted to have *one space* after type casts. Making it work was easier than I thought. You may check my fork (https://github.com/monoblaine/StyleCopAnalyzers/commits/space-after-type-cast) if you're still interested.

**Comment by xperiandri** [comment]
Cool, thanks @monoblaine

**Comment by madhavpatel6** [comment]
Did this get checked in?

**Comment by sharwell** [comment]
@madhavpatel6 StyleCop Analyzers does not support styles where a space follows a cast. Other analyzer packages, such as the [Visual Studio formatter](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#csharp_space_after_cast) and [dotnet-format](https://github.com/dotnet/format) may support this.

**Comment by YoshiRulz** [comment]
This is now covered by the built-in rule IDE0055; set [`csharp_space_after_cast = true`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options#csharp_space_after_cast) in your EditorConfig file.
