### ISSUE TITLE
Allow configuration of SA1311:StaticReadonlyFieldsMustBeginWithUpperCaseLetter

### ISSUE THREAD

**Issue by adamralph** [DotNetAnalyzers/StyleCopAnalyzers#2191]
I always switch this rule off when using StyleCop, but it seems it is not currently configurable by StyleCop.json.

**Comment by sharwell** [comment]
Since StyleCop Analyzers ties directly in with the new compiler, we use the compiler's built-in mechanism (ruleset files) for all enabling/disabling of rules. You can find a link to more information about these files in the [project readme file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

**Comment by adamralph** [comment]
Ahhhh, yes of course. Ruleset files. I keep forgetting that Roslyn analyzers tie in with them. Thanks.
