### ISSUE TITLE
Cannot disable rule for specific Namespace

### ISSUE THREAD

**Issue by HakooDesai** [DotNetAnalyzers/StyleCopAnalyzers#2232]
I am trying to disable one rule for namespace wide, but it's not working,

I added below line in GlobalSuppressions.cs

```csharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(
    "StyleCop.CSharp.MaintainabilityRules",
    "SA1400:Access modifier must be declared",
    Justification = "testing",
    Scope = "namespace",
    Target = "Abc.TestStyleCop")]
```

What could be done?

Thanks,
Hakoo Desai.

**Comment by bjornhellander** [comment]
Every diagnostic is "targeting" a specific part of a file, for example a member or a class. You can only suppress diagnostics targeting a specific part, not diagnostics targeting anything inside a specific part.

Your attempt means please suppress all SA1400 diagnostics targeting namespace "Abc.TestStyleCop". That will not work since SA1400 targets classes, interfaces, members etc. Never namespaces...

You can have a different ruleset for a specific project or suppress messages on a case-by-case basis.

Could you explain more about your situation, for example why you want to suppress them in a specific namespace?

**Comment by bjornhellander** [comment]
You can also have look at #2108

**Comment by HakooDesai** [comment]
In ASP.NET Webforms, I have .ascx and .ascx.cs and associated .js files as well. All these files under Abc.UserControls. So, I am trying to suppress the warnings for Abc.UserControls.*. 

Resolving SA1400, changes the Capitalization in .ascx.cs but not in .ascx and .js which has string form. And this is breaking the pages and as it is Sitefinity, there is no way that I can check whole website for errors.

I did my best to create template which Suppress the types under Abc.Usercontrols.

But just wondering if there is another good way??

**Comment by bjornhellander** [comment]
No trivial way, that I know of.

If it's possible to move this namespace to a separate project, that would be my personal choice. Then you can have a more relaxed ruleset file for that project.

You can also suppress the warnings in each applicable file using this line:
`#pragma warning disable SA1400 // Access modifier must be declared`
But if there's a lot of files, this gets boring quickly...

**Comment by bjornhellander** [comment]
Did you mean to write SA1300 instead of SA1400?
In that case the file-by-file suppression would be something like this:
`#pragma warning disable SA1300 // Element must begin with upper-case letter`

Otherwise I would appreciate if you could provide an example, because SA1400 should not affect capitalizationas as far as I understand.

**Comment by sharwell** [comment]
@HakooDesai In StyleCop Analyzers 1.0, the only suppression we performed was detecting generated code. Starting with the 1.1 release, we turned even generated code detection over to Roslyn so *all* warning suppressions are entirely managed by the compiler itself. This would be a question to file here:
https://github.com/dotnet/roslyn

**Comment by icnocop** [comment]
For reference, an enhancement request has been filed here: https://github.com/dotnet/roslyn/issues/486.
