### ISSUE TITLE
SA1616 working with IntelliSense but not in Build

### ISSUE THREAD

**Issue by koenigst** [DotNetAnalyzers/StyleCopAnalyzers#2246]
The StyleCop rule SA1616 correctly highlights missing documentation in the Visual Studio 2015 editor but when the project is built the warning doesn't appear in the error list. This leads to problems as the CI-Server is not able to verify that the developer complies with the documentation guidelines.

I attached a minimal working sample which reproduces the error when using Visual Studio Enterprise 2015 Update 3.

[StyleCopRepro.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/636978/StyleCopRepro.zip)

Other rules might also be affected (e.g. SA1514) but I don't have a complete list of the rules that don't work.

**Comment by vweijsters** [comment]
Documentation analysis will not be done when building if XML documentation generation is disabled for a project. This is unfortunately a limitation of the Roslyn stack. We added the SA1652 rule to signal this problem, but in the example this rule is disabled, which is why you are not seeing it.

In order to work around this problem I strongly suggest that you leave SA1652 enabled if you want any of the SA16xx rules active.
