### ISSUE TITLE
SA1305 is ignoring exceptions in stylecop.json

### ISSUE THREAD

**Issue by salixzs** [DotNetAnalyzers/StyleCopAnalyzers#2249]
After latest update (1.1.0-Beta1) I got many SA1305 (Hungarian notation violations).
I have bunch of parameters and variables named "dbVariable" to distinguish them from dtoVariable.
"db" is added to stylecop.json file, which is located in solution root folder only (I guess it should "inherit" for projects in subfolders).
```json
{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "documentationRules": {
      "companyName": "client name",
      "copyrightText": "Copyright (c) {companyName}. All Rights Reserved.",
      "xmlHeader": false,
      "fileNamingConvention": "metadata"
    },
    "indentation": {
      "indentationSize": 4,
      "tabSize": 4,
      "useTabs": false
    },
    "layoutRules": {
      "newlineAtEndOfFile": "allow",
      "allowConsecutiveUsings": false
    },
    "orderingRules": {
      "usingDirectivesPlacement": "insideNamespace",
      "systemUsingDirectivesFirst": true,
      "blankLinesBetweenUsingGroups": "allow"
    },
    "namingRules": {
      "allowCommonHungarianPrefixes": true,
      "allowedHungarianPrefixes": [
        "db"
      ]
    }
  }
}
```
It seems either rule does not pick up configuration file, either allowed prefixes in it.

**Comment by bjornhellander** [comment]
Your configuraton file will not be read just because you add it in the solution folder. It needs to be explicitly added to each project you want it to apply to. Instructions on how to do that can be found in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md

**Comment by salixzs** [comment]
Thanks.
