### ISSUE TITLE
SA1623 - Incorrect Error on Read-Only Peoperty

### ISSUE THREAD

**Issue by J4Sander** [DotNetAnalyzers/StyleCopAnalyzers#2253]
Consider a read only property with read/write verbiage copypasta:
```
/// <summary>  
/// Gets or sets the path to the object's class.  
/// </summary>  
public ManagementPath ClassPath => this.managementObject.ClassPath;
```

SA1623 tags this with the misleading message "text must begin with: Gets", and auto-fix changes the summary to "Gets gets or sets".

**Comment by bjornhellander** [comment]
The error is correctly reported. Since there is no setter, the summary should start with "Gets" instead of "Gets or sets". I do however agree that the message might be seen as misleading, since the summary actually does start with "Gets". And the code fix must certainly messes up.

In 1.1.0-beta001, the code fix works as expected, but the error is now reported as SA1624 which seems wrong to me since this has nothing to do with the accessibility of the property's accessors.

This is the message I get with the beta version:
> Warning SA1624: Because the property only contains a visible get accessor, the documentation summary text must begin with 'Gets'. The documentation text within a C# property’s &lt;summary&gt; tag takes into account all of the accessors within the property, but one of the accessors has limited access.

**Comment by vweijsters** [comment]
Marking this a bug, as SA1623 should be raised in this case.

**Comment by bjornhellander** [comment]
I can fix this
