### ISSUE TITLE
Is there a way to create custom rule in C#?

### ISSUE THREAD

**Issue by RodionovDmitry** [DotNetAnalyzers/StyleCopAnalyzers#2265]
Good day,

In StyleCop there was a way to create custom rule. Is it still possible?

**Comment by sharwell** [comment]
StyleCop Analyzers does not provide any infrastructure to aid in developing custom rules. However, it doesn't really need to because the compiler already does that. Custom rules have the form of additional independent analyzer packages. You can install any number of Roslyn-based analyzer packages into your project to get the complete analysis you want.

**Comment by RodionovDmitry** [comment]
Figured out that it is easier to create my own custom analyzer and switch off some StyleCop rules. 
Cheers

**Comment by normanhh3** [comment]
This [Getting Started with Roslyn Analyzers](https://msdn.microsoft.com/en-us/library/mt162308.aspx) seems relevant for folks like me stumbling upon this question.
