### ISSUE TITLE
Update Documentation for VS 2017 .NET Core Projects

### ISSUE THREAD

**Issue by RehanSaeed** [DotNetAnalyzers/StyleCopAnalyzers#2305]
The documentation for VS 2017 .NET Core projects needs to be updated:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DotNetCli.md

In particular, I'm interested in finding out how to create and use a custom .ruleset file.

**Comment by msmolka** [comment]
here is a link how to do that:
[https://www.linkedin.com/pulse/supporting-roslyn-analyzers-visual-studio-2017-net-core-jake-brandt](https://www.linkedin.com/pulse/supporting-roslyn-analyzers-visual-studio-2017-net-core-jake-brandt)

**Comment by nover** [comment]
I'm working on a PR to update the documentation - just had to go though the upgrade on an existing project

**Comment by nover** [comment]
PR created: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2311

**Comment by benleonard101** [comment]
When will a stable release for .net core & vs 2017 be released that has a GUI for the rules?

**Comment by mattfrear** [comment]
@benleonard101 you can double-click on a .ruleset file and it opens in a GUI - doesn't that work for you?

**Comment by benleonard101** [comment]
@mattfrear after installing stylecop.analyzers I had to manually add a ruleset and add rules. Even at that, the only way currently functioning to disable a rule is to suppress them in the properties of the project. Older examples online showed the ruleset automatically added to the project and when clicking that, showed all the stylecop rules which could be deselected. Is the change in function due to .netcore moving from json to csproj?

**Comment by mattfrear** [comment]
@benleonard101 I don't know much about this as I'm only using Stylecop.Analyzers for the first time myself today. I have spent all day on it today but have managed to get it working, although I found it very fiddly. 

I added the ruleset file [here](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.ruleset) to my project, added a stylecop.json file to my project, added this to my .csproj

      <PropertyGroup>
        <CodeAnalysisRuleSet>StyleCop.Analyzers.ruleset</CodeAnalysisRuleSet>
      </PropertyGroup>
     <ItemGroup>
        <AdditionalFiles Include="stylecop.json" />
      </ItemGroup>

Build, and I get warnings. If I want to disable them I double click the .ruleset file and the GUI opens, and I can disable them via the checkbox there. I am running VS 2017 Enterprise.

What I did find was that if I had stylecop configured on say Project A, and project B references A, then that also will get stylecop warnings and I think the .ruleset of A wouldn't be respected in project B. The fix I found in another github comment, was to add PrivateAssets="All" to your NuGet package reference. Or add the same .ruleset file to project B and add the same xml above to project B's csproj. (I need to now try and share a .ruleset instead of copying it everywhere).

    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" PrivateAssets="All" />

Like I said, I'm no expert, but maybe this will help you.
