### ISSUE TITLE
specify stylecop.json at build-time, instead of modifying csproj

### ISSUE THREAD

**Issue by SurajGupta** [DotNetAnalyzers/StyleCopAnalyzers#2412]
Is there a way to specify a stylecop.json file to use at build-time instead of having to modify the csproj?  I'm at a company with lots of VS solutions and it's not tenable to rely on developers to setup their projects properly.  At built-time, I want to enforce a centralized/company-wide stylecop.json without having to hack the csproj.

Seprately, but related, I don't want to rely on developers installing the nuget-package.

**Comment by sharwell** [comment]
> Is there a way to specify a stylecop.json file to use at build-time instead of having to modify the csproj?

Not specifically. You could create a NuGet package which contains a stylecop.json file and a **.props** or **.targets** file which modifies the build to use it. We tried to do something like this in the past, but it proved inconsistent at best and we eventually reverted it in #1788. You may have a more controllable environment at your company where the approach would work.

If you create an internal NuGet package for this purpose, you can make it depend on StyleCop.Analyzers so you don't have to manually install two packages.

> Seprately, but related, I don't want to rely on developers installing the nuget-package.

Someone will need to install a NuGet package as a one-time thing in each project where you want the analyzers enabled. There are alternatives, but they are even more manual so that seems to defeat the purpose.

**Comment by SurajGupta** [comment]
Thanks so much!  My team landed on the same idea - have an internal nuget package.
