### ISSUE TITLE
Is it possible to use one or more of the analyzers directly in a test project?

### ISSUE THREAD

**Issue by gpetrou** [DotNetAnalyzers/StyleCopAnalyzers#2449]
Lets say we have a project that has a corresponding test project and we wanted to implement something like https://www.strathweb.com/2015/09/using-roslyn-and-unit-tests-to-enforce-coding-guidelines-and-more/ in order to enforce certain code guidelines.
Is it possible to use one of the analyzers in such a test?
I see that many of the StyleCopAnalyzers classes are internal.

**Comment by sharwell** [comment]
StyleCop Analyzers doesn't have a public API [by design](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/b371a67cd73c3344f7545c164dee2946ead8b8b0/StyleCop.Analyzers/StyleCop.Analyzers.Test/PublicApiTests.cs#L15-L17), but it's an open source project licensed under the Apache 2.0 license, which allows the code to be used in other projects subject to the conditions in the license.

**Comment by gpetrou** [comment]
I see. Would you consider adding one public class that can be used like StyleCopTester?
I mean just a public method that accepts the list of files and the id of the rule you want to check. This way you wouldn't have to expose/maintain the internal classes as a public API.

**Comment by sharwell** [comment]
The purpose of the current unit test is to ensure we have no downstream dependencies, which could e.g. be impacted by our assembly versioning policy. It may make more sense to create an independent tool which functions in this manner.
