### ISSUE TITLE
Don't check autogenerated files

### ISSUE THREAD

**Issue by YYProbe** [DotNetAnalyzers/StyleCopAnalyzers#2490]
Some files like AssemblyInfo.cs, *.Designer.cs, *.g.cs and some others are generated by Visual Studio and should not be checked by static analyzers.

**Comment by sharwell** [comment]
Starting with StyleCop Analyzers 1.1.0, all handling of exclusions is performed by Roslyn. If you are having trouble with a particular warning in a particular generated file, let us know which diagnostic ID and which file. It's probably a case we've had to deal with before. :smile;

**Comment by YYProbe** [comment]
SA1633 in AssemblyInfo.cs
SA1028 in auto-generated header of GlobalSuppressions.cs 😃

**Comment by sharwell** [comment]
> SA1633 in AssemblyInfo.cs

If this is an SDK project (.NET Core), there's not much you can do here until this is fixed in MSBuild (see #2314). In other cases, this is a legitimate issue that should be fixed by modifying the file.

> SA1028 in auto-generated header of GlobalSuppressions.cs

Templates are not considered generated files, so unless you have modified your build to create this file during the build process this is a legitimate report that should be corrected by modifying the file.
