### ISSUE TITLE
SA1636: Support all built in variables

### ISSUE THREAD

**Issue by rsking** [DotNetAnalyzers/StyleCopAnalyzers#2492]
In StyleCop, for the copyright text, the following variables were supported

$USER_LOGIN$, $USER_NAME$, $FILENAME$, $CURRENT_YEAR$, $CURRENT_MONTH$, $CURRENT_DAY$, $CURRENT_TIME$, $CREATED_YEAR$, $CREATED_MONTH$, $CREATED_DAY$, $CREATED_TIME$, $MODIFIED_YEAR$, $MODIFIED_MONTH$, $MODIFIED_DAY$, $MODIFIED_TIME$, $ACCESSED_YEAR$, $ACCESSED_MONTH$, $ACCESSED_DAY$, $ACCESSED_TIME$

At the moment only $FILENAME$ is supported as {fileName}. All these variables should be supported in the new {variableName} format.

**Comment by sharwell** [comment]
Of the above items, only `$FILENAME$` is deterministic for a given file. The others won't work properly across source control systems and development teams.

The one that could work in theory is the `$CREATED_*$` items. However, these items only work when creating new files. When attempting to correct an invalid header in an existing file, the code fix for these items would produce an incorrect result. Since these items are not conducive to a proper detection+fix feature, it would be better to correct the style for a project to no longer rely on these values.
