### ISSUE TITLE
Code fix for CS0246 doesn't work with SA1208 and SA1210

### ISSUE THREAD

**Issue by a-jackson** [DotNetAnalyzers/StyleCopAnalyzers#2547]
Not sure if this is something you can fix but when I'm missing a using directive and I get CS0246 and use the code fix to insert the missing using. It is often added in the wrong place (usually at the end) and doesn't seem to honour SA1208 and SA1210. I then have to go up the top of the file and use code fix again to reorder them which works.

Is it possible to modify the behaviour of the fix for CS0246 to put it in the correct place in the first place?

**Comment by sharwell** [comment]
Typically, when this problem occurs it's due to a mismatch between the built-in "Place System using directives first" setting and the stylecop.json settings that affect SA1208. If you are using Visual Studio 2017, you can configure the Visual Studio behavior with an .editorconfig file:

https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#usings

Otherwise, you'll need to check Tools &rarr; Options to verify the option.

**Comment by a-jackson** [comment]
Thanks. That worked. I had no idea VS supported .editorconfig now.
