### ISSUE TITLE
Linked stylecop.json not being used

### ISSUE THREAD

**Issue by cnshenj** [DotNetAnalyzers/StyleCopAnalyzers#2725]
Here is the repository that can be used to repro the issue: [https://github.com/cnshenj/StyleCopDemo](https://github.com/cnshenj/StyleCopDemo).

A `stylecop.json` (which exists outside the project directory) is added to the project as a link. It can be opened in VS2017 properly. However, when building, the settings (e.g. copyright text) are not being used by StyleCopAnalyzers, generating warnings (or errors since the project treats warnings as errors).

**Comment by sharwell** [comment]
The linked item was added with the wrong item type. It needs to be `AdditionalFiles` instead of `Content`. See the following page for more information:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md

**Comment by IanBFarrell** [comment]
I am having a similar issue. I have set the Build Action to "C# analyzer additional file" because I am using .net core and it still does not seem to use my stylecop.json file.

I know this because I have using Directives outside namespace and my Json file is configured to have placement outside, but StyleCop keeps complaining about it..

**Comment by sharwell** [comment]
@IanBFarrell Can you open a new issue for that and include a copy of your project file?

**Comment by IanBFarrell** [comment]
Will do. Thank you
