### ISSUE TITLE
Analyzer incorrectly suggests documenting methods marked as "internal" and incorrectly says to make internal fields private.

### ISSUE THREAD

**Issue by AraHaan** [DotNetAnalyzers/StyleCopAnalyzers#2777]
The Analyzer is dumb for cases like zlib.net where it has tons of internal fields that are shared internally with it's streams to make things like the ``ZStream``, ``ZInputStream``, and ``ZOutputStream`` work as expected. However the analyzer (even with latest beta) says to make them private, and in which case I had to hack them into properties to shut it up because otherwise the project would not compile as the internal fields used in the streams would say that it is ``inaccessible due to it's protection level.``. Please fix this annoyingness I had to turn off the documentation check as it also incorrectly gripes about not having a internal method or properties seen by only the assembly itself to be documented. Not everyone want their internal methods to appear in their ``<assembly output file name>.xml`` documentation file.

**Comment by sharwell** [comment]
> ... says to make internal fields private ...

This is the expected behavior of [SA1401](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1401.md).

> ... documentation check ... gripes about not having a internal [members] be documented ...

This is the default behavior, but is configurable via the [`documentInternalElements`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#documentation-requirements) property.

**Comment by AraHaan** [comment]
Ah, interesting, why is the default value for that is true, but private ones are false?

**Comment by sharwell** [comment]
> Ah, interesting, why is the default value for that is true, but private ones are false?

It is based on the following abstract observations:

* Developers should not need to understand the internal implementation details of a type in order to use it correctly. The documentation of the type and its members should be sufficient.
* Implementations of a type should be simple enough that the intent/behavior of `private` elements is clear even without documentation.

**Comment by sharwell** [comment]
📝 Even though SA1600 is likely not changing as a result of this bug, reviewing the tests in response to this bug report led directly to improvements for this rule, including some bug fixes related to the new C# 7.2 accessibility `private protected`. 👍
