### ISSUE TITLE
SA1500 - Wrong indentation (v1.1.0-beta009)

### ISSUE THREAD

**Issue by MrMikeJJ** [DotNetAnalyzers/StyleCopAnalyzers#2795]
Hi,
After applying SA1500 fix it rule, the indentation of the { is than it should be. Please see the screenshot.
thanks
Mike
![image](https://user-images.githubusercontent.com/5191401/47167080-92696000-d2f5-11e8-959a-54480f566f12.png)

(Possible cause, I have visual studio setup to use Tabs - set to 8 spaces per tab. This { has been indented using spaces, at 4 spaces per tab)

**Comment by MrMikeJJ** [comment]
The reason i raised this, is i was sure that in the old version (1.0.2) - the fix used the editor's settings, without a stylecop.json file. (I have tested that this morning and confirm this is the case).
It appears that this behaviour changed with v1.1.0-beta001.
If that is a deliberate change, please close this :)

**Comment by sharwell** [comment]
It's not a deliberate behavior that we ignore the editor settings. However, the 1.1.0 release added support for specifying indentation behavior in stylecop.json, and we needed to provide a default value for cases where it is not specified. Since the indentation settings from .editorconfig are not available through the current APIs and the editor settings are not consistent from machine to machine, we chose to provide a default consistent with the StyleCop default and ignore other sources.
