### ISSUE TITLE
StyleCopAnalyzers metadata dll could not be found when linked .ruleset file

### ISSUE THREAD

**Issue by veronika793** [DotNetAnalyzers/StyleCopAnalyzers#2827]
Hi, i am having the following issue: 
We have multiple projects - (a lot of them class libraries targeting .NET Standard 2.0 or .NET Core 2.1) in solution with references to each other with installed analyzer (version 1.1.0-beta009). I've tested it with installation of the analyzer per single project and for entire solution. The problem occurs when i add the path for the shared .ruleset file in the .csproj file. 
`    <CodeAnalysisRuleSet>../Analyzers/stylecop.ruleset</CodeAnalysisRuleSet>
`
After rebuild tho i get multiple errors from the projects that are referencing the one configured(there is .ruleset file linked)
`Error CS0006 Metadata file .. could not be found.`
The  ruleset  configurations are applied tho. Without adding the `.ruleset ` file not problems occurred.
Do you have any ideas or suggestions about what is happening ?

Here is sample project with same problem: https://github.com/veronika793/TestRepo

**Comment by veronika793** [comment]
Is there any solution about this issue ?

**Comment by sharwell** [comment]
In the sample project, SA1508 is configured with Error severity:

https://github.com/veronika793/TestRepo/blob/4ca66c2cd17ca66281dbd798d6d82f6bcefb9016/Analyzers/rules.ruleset#L149

The error is then reported on the following line, and the Error severity prevents the compiler from creating FirstProject.dll until the error is corrected:

https://github.com/veronika793/TestRepo/blob/4ca66c2cd17ca66281dbd798d6d82f6bcefb9016/FirstProject/Item.cs#L15

The CS0006 reports are the compiler saying SecondProject and ThirdProject cannot be compiled until FirstProject compiles successfully, because they have a project reference to it.
