### ISSUE TITLE
SA0001 when building Razor view assemblies after update from 1.0.2 to 1.1.118

### ISSUE THREAD

**Issue by Dennis-Petrov** [DotNetAnalyzers/StyleCopAnalyzers#3034]
Greetings!
Just have updated StyleCopAnalyzers from 1.0.2 to 1.1.118, and all my Razor projects generate SA0001 when running `RazorCoreCompile` task.

MSBuild produces this output (compiler command line is reduced for readability, but I can post it if required):

> Target RazorCoreCompile:
> 1>  Building target "RazorCoreCompile" completely.
> 1>  Output file "obj\Debug\netcoreapp2.2\TerraLink.xDE.Portal.Views.dll" does not exist.
> 1>  Task "Csc"
> 1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702,2008,1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETCOREAPP;NETCOREAPP2_2 /errorendlocation /preferreduilang:en-US ... /warnaserror+:NU1605
> 1>    Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn
> 1>    Microsoft (R) Visual C# Compiler version 3.3.1-beta3-19461-02 (2fd12c21)
> 1>    Copyright (C) Microsoft Corporation. All rights reserved.
> 1>    CSC : warning SA0001: XML comment analysis is disabled due to project configuration
> 1>  Done executing task "Csc".
> 1>Done building target "RazorCoreCompile" in project "Portal.csproj".

Rule description says, that

> A violation of this rule occurs when a compilation (project) contains one or more files which are parsed with the DocumentationMode set to None. This most frequently occurs when the project is configured to not produce an XML documentation file during the build.

But XML docs are turned on. All of my project import shared MSBuild props file with this:

```
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
```

Output folder contains XML docs file for every built assembly.

I have no idea where is the problem.
Any suggestions?

**Comment by sharwell** [comment]
`RazorCoreCompile` does not set the `DocumentationFile` property when invoking CSC. Here is the definition for normal C# projects:

https://github.com/dotnet/roslyn/blob/80c7647d1bebd56b164605a678f93de497e9c8ae/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L77

Here is the definition for Razor:

https://github.com/aspnet/Razor/blob/5439cfe540084edd673b7ed626f2ec9cf3f13b18/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets#L108-L172

It will not be possible to use documentation-related analyzers in Razor until this bug is fixed. I believe the best place to report the bug is [aspnet/Razor](https://github.com/aspnet/Razor).
