### ISSUE TITLE
SA1649 ("File name should match first type name") if first type is an enum

### ISSUE THREAD

**Issue by Trolldemorted** [DotNetAnalyzers/StyleCopAnalyzers#3234]
Take this `FooBar.cs`:
```
public enum FooBar
{
    Something,
}

public static class FooBaarExtensions
{
    public static string ToUserFriendlyString(this FooBar fsr)
    {
        return "foofoo";
    }
}
```
It procudes a SA1649, but the file name does match the first type name.

**Comment by sharwell** [comment]
From the implementation side, this is occurring because we look for `TypeDeclarationSyntax` here:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/a2834334f86c96f33c35e2b62e0146c253fa9de5/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1649FileNameMustMatchTypeName.cs#L95-L100

`EnumDeclarationSyntax` extends `BaseTypeDeclarationSyntax` so it isn't picked up by this. `DelegateDeclarationSyntax` extends `MemberDeclarationSyntax` so it also is ignored.

I would be in favor of changing SA1649 to support `enum` and `delegate` provided the following conditions are met:

* For a file containing more than one type, prefer to use the first `TypeDeclarationSyntax` for the check.
* Only check the file name for an `enum` or `delegate` if it is the _only_ top-level type defined in the file.
