### ISSUE TITLE
VS Code Experience

### ISSUE THREAD

**Issue by Trolldemorted** [DotNetAnalyzers/StyleCopAnalyzers#3377]
As of now, adding StyleCop.Analyzers to a project does not result in a confortable dev environment in vs code. To be precise:
- you cannot auto apply fixes which you could in the real VS
- you don't see warnings unless you trigger the right build action within vs code
- warnings don't disappear if you fix them in vs code, only after you trigger a new build action
- all warnings disappear if you do two builds subsequently without changing code

Is there anything I can do to have a better developing experience in vs code?

**Comment by sharwell** [comment]
I would recommend filing this at [dotnet/roslyn](https://github.com/dotnet/roslyn), since analyzers don't have control over how they are used. I don't use VS Code for C# projects myself, so I'm not sure what its current capabilities are. Hopefully someone on the Roslyn project will be able to provide more information.
