### ISSUE TITLE
SA1210 is inconsistent with IDE's Remove and Sort Usings (casing)

### ISSUE THREAD

**Issue by alexanderjung-sdxag** [DotNetAnalyzers/StyleCopAnalyzers#3467]
I have a reference (over wich I have no control) which does not adhere to naming conventions (unfortunately) and uses lowecase for namespaces.

The IDE sorts this by lowercase first, SA1210 checks case insensitive:

IDE:
using company.xxx;
using Company.AAA;

SA1210 expects:
using Company.AAA;
using company.xxx;

**Comment by CyrusNajmabadi** [comment]
I'm genuinely curious why StyleCop sorts this way.

**Comment by manfred-brands** [comment]
Case insensitive sorting, what users expect.

**Comment by sharwell** [comment]
@CyrusNajmabadi Visual Studio and the C# experience generally sorts things in a case-insensitive manner first, and only uses case-sensitive as a tie-breaker.

**Comment by CyrusNajmabadi** [comment]
I see. That doesn't match my expectation at all. But I also don't think of have an issue changing this. The only concern is that this would break anyone who was currently compliant with how things are sorted today and will runs into this situation. 

Note that this sorting has been how we've sorted things since 2003. So I'm feeling it would be better to just keep the status quo vs risk affecting people based on one report.

**Comment by sharwell** [comment]
@CyrusNajmabadi Visual Studio 2012 sorted case-insensitive
