### ISSUE TITLE
Is there an editorconfig equivalent for most of the rules, and where are they maintained?

### ISSUE THREAD

**Issue by sjd2021** [DotNetAnalyzers/StyleCopAnalyzers#3531]
I'm having somewhat of a hard time upgrading to the supposed new way of configuring rules. In my specific case, I would like to pull in [this rule](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md) to my team's projects. I have been maintaining all of the rules in an editorconfig, but I can't seem to find an equivalent for requiring consistent orderings so people aren't adding a constructor in the middle of all of their properties.

Are there any available options for this right now?

**Comment by sharwell** [comment]
StyleCop Analyzers can be configured using .editorconfig (or better, .globalconfig) instead of using ruleset files.

The code style package in the SDK includes some style rules with special configuration options that also appear in these files. In some cases, there is overlap between the SDK style rules and StyleCop Analyzers, but for many rules there you will find behavior differences and/or cases where only one of the two packages provides a specific feature.

I'm not aware of any other package which currently implements the functionality from SA1201.
