### ISSUE TITLE
SA1516 without a line number

### ISSUE THREAD

**Issue by kglundgren** [DotNetAnalyzers/StyleCopAnalyzers#3565]
I can't see the error anywhere in my files, and I can't double click on the error in the error list in Visual Studio to get to it either.
It comes from a "CSC" file apparently. 

![image](https://user-images.githubusercontent.com/56938604/195560942-610a2f56-4472-468e-a21d-28e9132c5b09.png)

**Comment by bjornhellander** [comment]
Hi! Based on the AD0001 about SA1201 throwing an exception, it looks like the StyleCop.Analyzers version you are using is too old for the c# language version you are using in your projects. There was a fix made in 2020 to protect from exceptions in SA1201, so that is why I assume that you are using an older version. I don't know if this is related to the thing you actually reported, but maybe we can focus on the AD0001 first, since that seems like a simpler problem? Can you upgrade to beta 435 and try again?

**Comment by kglundgren** [comment]
Thanks for replying! I can't find the beta release in the Visual Studio nuget package management window. These are the versions I can see: 
![image](https://user-images.githubusercontent.com/56938604/196374230-e2bc5271-ee92-49fa-83de-815a6a60d1b8.png)
Is there another way to install the beta version?

**Comment by bjornhellander** [comment]
There is a checkbox called "Include prerelease". See for example the screenshot from this question:
https://stackoverflow.com/questions/54984996/nuget-activate-include-prerelease-via-config-file

**Comment by kglundgren** [comment]
After upgrading to version 1.2.0-beta.435 the warning went away. Thanks!

**Comment by sharwell** [comment]
Duplicate of #3242
