### ISSUE TITLE
StyleCop Warnings is not not displayed.

### ISSUE THREAD

**Issue by leapold** [DotNetAnalyzers/StyleCopAnalyzers#3567]
Hello,
I have big class that contains 10000 lines.
When I run StyleCop I heve no warning in the output but there are many.
I integrated StyleCop in the Resharper and I can see many warning(blue underline that Resharper marks them )
Example :There is no this before variable
------ StyleCop completed ------
========== Violation Count: 0 ==========
 
![4](https://user-images.githubusercontent.com/11920073/195854512-74558daa-80a6-4742-b7ae-9997eede21bf.JPG)

**Comment by bjornhellander** [comment]
Hi! I do not recognize the output. Are you really using "StyleCop.Analyzers" (this project)? If you are using the StyleCop plugin to Resharper or "StyleCop Classic", then you have come to the wrong place.

**Comment by bjornhellander** [comment]
Any response, @leapold?

**Comment by leapold** [comment]
Probably, this is wrong place. i am using https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop

**Comment by bjornhellander** [comment]
It is. You are using what is commonly called "StyleCop Classic" while this is "StyleCop Analyzers". The page you referred to has a link to their GitHub project, but it seems not to be that active anymore. Maybe consider changing package? :-)

Feel free to close this issue if you are content with the answer, since I can not do it for you.
