### ISSUE TITLE
StyleCopAnalyzers analyzes code generated by other analyzers/generators

### ISSUE THREAD

**Issue by hugener** [DotNetAnalyzers/StyleCopAnalyzers#3582]
I recently noticed StyleCopAnalyzer reporting errors in files added/generated by other analyzers/generators.

Has anyone else noticed this?
I'm not sure if it's a roslyn issue or an issue of StyleCopAnalyzer.

**Comment by bjornhellander** [comment]
All analyzers in this package are configured to not run on generated code, but what is considered generated code is up to Roslyn, so this is not an issue in StyleCop Analyzers.

Roslyn recognizes `// <auto-generated/>` comments, which (as far as understand) should be emitted by generators. This is also respected by other tools like Resharper. **This is the correct way to solve the problem.**

Besides that, Roslyn has some heuristics based on the file name, but I have no details about that.

If this is not enough, there seems to be a way to explicitly tell Roslyn to treat certain files as generated. I have not used this myself, but I found this description: https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-generated-code

Please feel free to close this issue if you understand the answer. This analyzer package has no control over your issue, since Roslyn already knows that it should not run these analyzers on generated code.

**Comment by bruno-brant** [comment]
@bjornhellander I'm a bit "late to the party" with Source Generators, but I'm working on a project [1] that does extensive use of it and StyleCop is analyzing that code. I would guess that Roslyn would know that code is generated, since it was created by a compiler feature, and therefore automatically mark it so that the analyzers can ignore it...? Is that correct? Or should source generators explicitly emit `// <auto-generated/>`? This seems very redundant. 

1. I'm coding in Godot using .NET classes.

**Comment by bjornhellander** [comment]
@bruno-brant I have almost zero experience on this, but based on the code generation that is being done in this repository, the compiler seems to understand. The generated files have suffix `.g.cs` and end up in a folder called `.generated`, which might be a part of the reason.

This file might also contain necessary things to make it behave like this, like `CompilerGeneratedFilesOutputPath`: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.csproj

**Comment by sharwell** [comment]
> Or should source generators explicitly emit `// <auto-generated/>`?

Source generators should explicitly mark themselves as generated. Be aware that marking them as generated also causes them to always default to `#nullable disable` (even if the project default is `enable`), so you'll also want to explicitly enable that feature by including `#nullable enable` in the generated code.
