### ISSUE TITLE
Regex.IsMatch(string, string) inside NamingSettings.ctor is causing 15.1% allocations

### ISSUE THREAD

**Issue by ninedan** [DotNetAnalyzers/StyleCopAnalyzers#3629]
Building a large project, found Regex.IsMatch(string, string) inside NamingSettings.ctor is causing 15.1% allocations, mostly due to constructing regular expression repeatitively. At least the regular expressions should be reused.
![image](https://user-images.githubusercontent.com/19536938/230456479-4ce51666-f6be-4cb7-802a-677d183130eb.png)

**Comment by ninedan** [comment]
Building a large .cs project, capturing a trace using PerfView. This stack is bad enough that any trace invoking it will show.

**Comment by bjornhellander** [comment]
My understanding was that Regex.IsMatch caches the instance, but maybe the cache isn't big enough for everything needed while compiling a large solution.

I am having problems actually measuring this, but changing to having a static field with the Regex instead of calling Regex.IsMatch seems trivial. Do you see any downsides to that, @sharwell?
