### ISSUE TITLE
SA1206 does not respect EditorConfig csharp_preferred_modifier_order option

### ISSUE THREAD

**Issue by jkoritzinsky** [DotNetAnalyzers/StyleCopAnalyzers#3660]
In the code snippet `static file class ElementsMarshallingCollectionSourceExtensions {}`, IDE0036 from the compiler puts the `file` keyword after the `static` keyword, but SA1206 says to put the `file` keyword before the `static` keyword.

**Comment by bjornhellander** [comment]
Regarding IDE0036, I do not experience the same behaviour that you are describing and https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036 also says it expects `file` before `static`, at least by default. Are you sure you read the IDE0036 hints correctly? If IDE0036 really is behaving the way you say without you having reconfigured the desired order, I suggest you file a bug report over at https://github.com/dotnet/roslyn.

**Regarding SA1206, this is the intended behaviour**. There are un-released bug fixes concerning the **code fix** for SA1206, but the diagnostics were correct before as well if I am not mistaken.

**Comment by jkoritzinsky** [comment]
Yes, I have IDE0036 configured to error in my build and it's causing an error if I do `file static`. This might be a bug on IDE0036 and not on SA1206.

**Comment by jkoritzinsky** [comment]
Found the problem. SA1206 doesn't respect the `csharp_preferred_modifier_order` editorconfig option, so when a custom value for that option is set, IDE0036 and SA1206 can get out of sync.

**Comment by bjornhellander** [comment]
See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md for a brief description of what SA1206 expects. And note that `file` is treated as an access modifier in SA1206, so it expects it to come first in your example. SA1206 is weaker in its ordering compared to IDE0036, since it only requires the three groups of modifers to be in the the expected order, without caring for the order within each group, whereas IDE0036 is more strict and requires the exact order you have specified (or according to its default).

If you want a customized modifier order, then turning off SA1206 and going with IDE0036 instead is the way forward for you, in my opinion. @sharwell, do you have another opinion on this?

**Comment by sharwell** [comment]
Yeah `file` is an access modifier:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/14245e2d8f2a86abd03f73d51b38acb40ddf6665/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/ModifierOrderHelper.cs#L50-L51

I believe this is the only logical classification for this modifier.

Since IDE0036 is strictly a more complete analyzer than SA1206, there is no need to run them both at the same time. The following are supported scenarios:

1. SA1206 enabled, but IDE0036 disabled
2. IDE0036 enabled, but SA1206 disabled
3. Both IDE0036 and SA1206 enabled, provided the modifier order defined by IDE0036 adheres to the partial order defined by [these buckets](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/14245e2d8f2a86abd03f73d51b38acb40ddf6665/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/ModifierOrderHelper.cs#L46-L72) for SA1206

While option 3 is supported, it is not recommended.
