### ISSUE TITLE
Rule SA1622 error doesn't fail msbuild

### ISSUE THREAD

**Issue by RenseSTA** [DotNetAnalyzers/StyleCopAnalyzers#3698]
Ive setup analysers to run on building my application. 
SA1622 doesn't work properly since it allows me to build while it has related errors. I have tried enabling other documentation rules and they work properly.
i'm on stylecop version 1.2.0-beta.507

**Comment by bjornhellander** [comment]
Hi!

I find it a bit difficult to understand exactly what you mean:
1) Have you configured SA1622 to report an error instead of a warning (which is the default behavior)?
2) The title says "msbuild". Do you mean that SA1622 is reported as an error inside Visual Studio, but not when running msbuild directly?
3) By "it allows me to build", do you mean that SA1622 is not reported at all, or is it reported as a warning instead and therefore does not fail the build?

Can you provide a link to a project where it doesn't work as expected?

**Comment by RenseSTA** [comment]
SA1622 is configured to report as an error,
sa1622 is reported as an error but it does not inhibit building like the other rules set as error,
It is reported but as an error but I can still build my application.
Unfortunately I cannot share a link to the project since it is a private company project

**Comment by sharwell** [comment]
@RenseSTA StyleCop Analyzers is not responsible for marking a build as failed.

If SA1622 is still being reported as a warning even though you set it as error, it should be reported here:
https://github.com/dotnet/roslyn

If SA1622 is showing up as an error, but the build is not failing, it should probably be reported here:
https://github.com/dotnet/msbuild
