### ISSUE TITLE
System.NullReferenceExceptions with v 1.1.118

### ISSUE THREAD

**Issue by WernerMairl** [DotNetAnalyzers/StyleCopAnalyzers#3814]
After the update to v1.1.118 (also updated to the latest (released nothing beta) net8.0 and VS bits I get a lot of Exceptions like this (that I never got with the versions before - multiple projects)...

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/10084630/75018c19-4771-419d-a27b-546f342604d5)

Is it under investigations (assuming a lot of people has the same problem) or I have to start to provide more details ??

BR
Werner

**Comment by bjornhellander** [comment]
1.1.118 is almost 5 years old and there has unfortunately only been beta releases since then. This is because of project policies related to quality requirements to make an official release, combined with not enough people helping out to keep up with the quick release cycle of the c# language and compiler. So right now, you need to use a beta release to get a good experience.

**Comment by sharwell** [comment]
Thank you @bjornhellander that is well-stated
