### ISSUE TITLE
SA1206 suggests a non-idiomatic placement of the required modifier.

### ISSUE THREAD

**Issue by mrudat** [DotNetAnalyzers/StyleCopAnalyzers#3846]
As far as I can tell, the preferred way to specify [required](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required) is:

```
public required string WeNeedThisString { get; init; }
```

And not, as SA1206 suggests:

```
required public string WeNeedThisString { get; init; }
```

**Comment by bjornhellander** [comment]
Which version are you using?

**Comment by bjornhellander** [comment]
I am unable to reproduct this with the latest beta

**Comment by mrudat** [comment]
The latest release available via NuGet.

**Comment by sharwell** [comment]
Duplicate of #3527

**Comment by bjornhellander** [comment]
@mrudat A clarification: We are assuming that you are using version 1.1.118, which is from 2019 and have big problems with modern c# features. Since then there has been only beta release, which is of course easy to miss when installing packages. If you want to have StyleCop.Analyzers installed and use modern c# features, you will have bad experience if you are not using the beta versions.

**Comment by 51dario51** [comment]
Is any official release of the current latest beta planned?
Of course we could simply update the package to the latest beta, but how safe is this beta?
