### ISSUE TITLE
[F.Rq.] Apply trailing newline rule SA1518 to Razor Pages (`.cshtml`)

### ISSUE THREAD

**Issue by YoshiRulz** [DotNetAnalyzers/StyleCopAnalyzers#3886]

**Comment by bjornhellander** [comment]
Because of how these analyzers are implemented, they are never run on .cshtml files. I personally think it would be easier for you to handle this yourself, in some other way. One way could be to write a unit test which scans your project folder for .cshtml files and checks the trailing newline.

I assume that you can also set insert_final_newline = true in an .editorconfig file. Visual Studio will then make sure that an edited file will have a correct trailing newline after saving it. It might not help if someone edits files in another editor, but it will give you most of effect you want.
