### ISSUE TITLE
Settings.StyleCop

### ISSUE THREAD

**Issue by bytenik** [DotNetAnalyzers/StyleCopAnalyzers#422]
Does this project obey Settings.StyleCop? If not, how can I disable a bunch of analyzers on a global (solution wide) scale?

**Comment by sharwell** [comment]
Hi @bytenik,

This is an interesting request. It makes sense, but I'm not sure if we'll actually want to implement it.

The settings are configured in the Code Analysis tab for project settings, and optionally stored in a Code Analysis Ruleset file [like this one](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.ruleset). You can configure settings for a solution by creating a ruleset file for one project, saving it, and then configuring other projects in the solution to use the same file.

I'm hoping to make this the long-term solution regarding this issue since it's the standard manner for users to configure Code Analysis (including but not limited to this implementation of the StyleCop rules).

**Comment by sharwell** [comment]
I just realized we could handle this as follows:

1. Code Analysis Ruleset files are the new and single *preferred* way to configure the rules at any scope.
2. Since we are distributing this analyzer through NuGet, we can create a **.targets** file to include in that package that automatically adds **Settings.StyleCop** as an "additional item", which is then accessible to analyzers. If an analyzer is disabled via that file but enabled according to the ruleset(s) in effect for the project, we will report a warning regarding the use of a non-standard configuration method and disable the diagnostic in code.

**Comment by hickford** [comment]
It's important to us that we can re-use our `StyleCop.Settings` or convert it to a `.ruleset`. Otherwise we can't upgrade https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1144

**Comment by sharwell** [comment]
@hickford Currently there are no "configurable" rules implemented in StyleCopAnalyzers. The rule set starts out with each option set to Warning. For any item you disabled in the StyleCop.Settings file, you can set it as disabled in the rule set as well.

I'd be interested to see your StyleCop.Settings file.

**Comment by sharwell** [comment]
@hickford To clarify the previous comment, the *only* configuration currently supported is the `Enabled` property from Settings.StyleCop. For example, if you have the following:

```xml
<Rule Name="FileHeaderMustHaveValidCompanyText">
  <RuleSettings>
    <BooleanProperty Name="Enabled">False</BooleanProperty>
  </RuleSettings>
</Rule>
```

Then you would set SA1640 to Disabled in the rule set.

**Comment by hickford** [comment]
Hi Sam. Thanks for your reply. That makes sense. Hopefully exact rules are less controversial than configurable rules (one team has stylecop configured to reject `this.`, another to enforce it). I like the ruleset format better, it lists rules by code rather than name.

Anyway here's our StyleCop.Settings 

  <StyleCopSettings Version="105">
    <GlobalSettings>
      <BooleanProperty Name="AutoCheckForUpdate">False</BooleanProperty>
    </GlobalSettings>
    <Parsers>
      <Parser ParserId="StyleCop.CSharp.CsParser">
        <ParserSettings>
          <CollectionProperty Name="GeneratedFileFilters">
            <Value>\.g\.cs$</Value>
            <Value>\.generated\.cs$</Value>
            <Value>\.g\.i\.cs$</Value>
          </CollectionProperty>
          <BooleanProperty Name="AnalyzeDesignerFiles">False</BooleanProperty>
        </ParserSettings>
      </Parser>
    </Parsers>
    <Analyzers>
      <Analyzer AnalyzerId="StyleCop.CSharp.NamingRules">
        <AnalyzerSettings>
          <CollectionProperty Name="Hungarian">
            <Value>as</Value>
            <Value>do</Value>
            <Value>id</Value>
            <Value>if</Value>
            <Value>in</Value>
            <Value>is</Value>
            <Value>my</Value>
            <Value>no</Value>
            <Value>on</Value>
            <Value>to</Value>
            <Value>ui</Value>
          </CollectionProperty>
        </AnalyzerSettings>
      </Analyzer>
      <Analyzer AnalyzerId="StyleCopPlus.StyleCopPlusRules">
        <Rules>
          <Rule Name="CodeLineMustNotEndWithWhitespace">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="CheckAllowedIndentationCharacters">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="CheckWhetherLastCodeLineIsEmpty">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="CodeLineMustNotBeLongerThan">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="MethodMustNotContainMoreLinesThan">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="PropertyMustNotContainMoreLinesThan">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="FileMustNotContainMoreLinesThan">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
          <Rule Name="AdvancedNamingRules">
            <RuleSettings>
              <BooleanProperty Name="Enabled">False</BooleanProperty>
            </RuleSettings>
          </Rule>
        </Rules>
        <AnalyzerSettings />
      </Analyzer>
    </Analyzers>
  </StyleCopSettings>

**Comment by sharwell** [comment]
@hickford I'm not sure what "AdvancedNamingRules" is, but if it's only a StyleCopPlus rule then it wouldn't be implemented here anyway. The "___MoreLinesThan" and "___LongerThan" rules don't meet our standard for object analysis, so they won't be included here either.

It's possible the only rules you need to disable are SA1027 (if you indent with hard tabs) and SA1028 (to allow trailing whitespace). However, I would consider enabling SA1028. The Beta 3 release was able to remove over 99% of trailing whitespaces automatically without any errors, and the Beta 4 release is able to remove everything except some relatively obscure syntax (#796, #821).

**Comment by otac0n** [comment]
In regards to including additional configuration, are you aware that Code Analysis uses `<CodeAnalysisDictionary />` (CustomDictionary.xml) items in the project?  This sounds like a reasonable approach for things like Hungarian notation.

You could make it such that any one- or two letter prefix is disallowed, unless it is included in the dictionary (or in your list of very common prefixes).

You could also use this approach for other configuration settings.

**Comment by sharwell** [comment]
Superseded by #892
