### ISSUE TITLE
Priorities for Alpha 5

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#474]
I propose the following areas of priority for Alpha 5:

1. Complete tests for items in the **Spacing** category. Analysis for all of these and code fixes for many are already implemented, but aren't enabled in the Alpha 3 release due to the testing requirement. **Yes this is my fault.** But it would still be nice to include them.
2. Complete code fixes for remaining items in the **Spacing** category.
3. Complete tests for other diagnostics that are already implemented.

Hopefully Alpha 4 comes out quickly and then we can move forward with additional rules for future releases.

**Obviously** this does not mean I will turn down contributions on other rules.

@macpak @pdelvo @camilojd  Any comments/concerns/suggestions?

**Comment by AArnott** [comment]
Personally, I'd rather see alpha 5 ship very soon, and save most of the issues tagged for alpha 5 for the next release. With the fix for auto-generated, and a few others that have come in recently, I have enough to get by in adopting this nuget package as I can disable the rules that aren't quite right yet. So I'd like alpha5 shipped very soon so I can actually check in the analyzer dependency.

**Comment by pdelvo** [comment]
I think so too. A lot happened since Alpha 4 and with 169 closed issues since the last milestone releasing a new alpha is a good idea. On the other hand Im actually pretty sure that next week at build a new (pre-)release of visual studio is going to be released which would mean that Alpha 5 would be relevant for not even a week. I would wait until next week. So I think we should use the weekend to test our code on a lot of code bases to find and fix remaining bugs until then.

**Comment by macpak** [comment]
IMO, if VS is to be released next week, we should wait.

**Comment by sharwell** [comment]
@AArnott I would like to see it shipped soon as well. With respect to the MS projects (that use slightly different rules), the following are low-hanging fruit. Any of them we get them addressed today will improve the experience, but I don't think we're missing anything critical.

* Currently both SA1308 and SA1310 must be disabled. If we address #688, then only SA1308 would need to be disabled.
* If #680 is not fixed, we need to mark SA1201 as disabled by default.
* #689 needs to be addressed or you'll have to disable SA1509.
* #690 or #691 (the latter is essentially trivial) needs to be addressed or you'll have to disable SA1504.
* #693 needs to be addressed or you'll have to disable SA1516.

**Comment by sharwell** [comment]
*Way to deliver* y'all. :sparkles:
