### ISSUE TITLE
SA1121: UseBuiltInTypeAlias

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#54]
http://www.stylecop.com/docs/SA1121.html

**Comment by pdelvo** [comment]
I unfortunatly started working on this without looking at this issue. So I have a second implementation of this. I will open a pull request for it because it contains a bunch of unit tests which should be usefull with your implementation as well.
I don't know if a code fix is needed for this because visual studio has a refactoring for this.

**Comment by sharwell** [comment]
We can talk about the code fix possibilities in #304.

I propose that we review pull request #306 and merge it, and then you update #350 to just address #303. Does this plan work for you? Also, can you help with the review of #306?
