### ISSUE TITLE
SA1126: PrefixCallsCorrectly

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#59]
http://www.stylecop.com/docs/SA1126.html

**Comment by sharwell** [comment]
It seems like this diagnostic is not needed now that we are using Roslyn for analysis (its `SemanticModel` tells us everything we need to know).

**Comment by sharwell** [comment]
I am planning to close this issue as **wontfix** because it is so vaguely worded. If we are in agreement on this, any specific functionality originally part of it can be proposed and implemented as part of new well-defined rules.

**Comment by vweijsters** [comment]
Sounds like a good plan.

As far as I could determine, the following scenarios should still be addressed:
- Usage of  `Equals(objA, objB)` and `ReferenceEquals(objA, objB)`
- A overridden method where the analyzer cannot decide if the developer intended to call the `this` implementation or the `base` implementation

**Comment by sharwell** [comment]
@vweijsters How might those scenarios be addressed?

:thought_balloon: For the second one, all of our analyzers currently assume that the intended target is the method that was actually called. That seems to be a reasonable assumption for a style checker.

**Comment by AArnott** [comment]
Is SA1126 the rule responsible for enforcing folks prefix `this.` everywhere? If that's the case, that's a valuable rule that I am eager to resume enforcing once StyleCop.Analyzers supports.

It's fantastic for when you write thread-safe code because it makes it abundantly clear whether you're reading or modifying instance state, or calling an instance method that might.

Please, let's support this rule.

**Comment by sharwell** [comment]
@AArnott That would be SA1101, and it's been available with a code fix since Alpha 3. In this project we actually have the severity for violations set to Error.

**Comment by AArnott** [comment]
I see. In that case, I agree with not implementing this diagnostic.

**Comment by naamunds** [comment]
@sharwell - is there currently a rule for enforcing that a reference to a class-level member is prefixed with the class's name?  This would be analogous to SA1101, but for `static` methods and variables, `const` variables, etc.

For example, if I define `class Person` with `const string JuniorSuffix = "Jr."`, I would want to enforce that references to JuniorSuffix within the Person class are written as `Person.JuniorSuffix` rather than just `JuniorSuffix`.

**Comment by sharwell** [comment]
@naamunds I am not aware of any such rule.
