### ISSUE TITLE
Prerelease versions should use "alpha.5" instead of "alpha005" format

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#674]
Picking an arbitrary number of leading zeros as part of an alphanumeric identifier isn't leveraging the semver rules and limits readability and comparability. See below for some relevant sections and emphasized sentences relevant to this.

From [semver.org](http://semver.org/)

> 9.A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Numeric identifiers MUST NOT include leading zeroes.** Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92

> 11.Precedence refers to how versions are compared to each other when ordered. Precedence MUST be calculated by separating the version into major, minor, patch and pre-release identifiers in that order (Build metadata does not figure into precedence). Precedence is determined by the first difference when comparing each of these identifiers from left to right as follows: Major, minor, and patch versions are always compared numerically. Example: 1.0.0 < 2.0.0 < 2.1.0 < 2.1.1. When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0. Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: **identifiers consisting of only digits are compared numerically** and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by vweijsters** [comment]
You are right as far as semantic versioning is concerned, but the leading zeros are a necessity because of limitations of NuGet (NuGet parses everything after the dash as alphanumerical, which is not in compliance with clause 11 of semver 2.0.0).

I suggest we don't change anything, as we don't want to get into the situation where -alpha.10 is considered lower in version than -alpha.2

(Also see [Top10 NuGet patterns](https://msdn.microsoft.com/en-us/magazine/jj851071.aspx))

**Comment by sharwell** [comment]
@AArnott You are quoting semver 2.0.0. The naming used to date is based on limitations in semver 1.0.0 (which is also the version @vweijsters is indirectly referencing). Previously NuGet did not support semver 2.0.0. That said:

1. Which version(s) of NuGet support semver 2.0.0?
2. While many users installing this package only work in Visual Studio 2015, that is not a requirement. It can be installed in projects that support Visual Studio 2010+, and will simply "light up" when the project is opened in 2015. As such, `nuget restore` for Visual Studio 2010+ cannot fail due to our naming convention.

**Comment by AArnott** [comment]
`nuget restore` should always work. That doesn't do any version comparison -- it just gets exactly the version that was installed previously.
The good question though to discuss is whether NuGet's `Install-Package` and `Update-Package` commands will correctly interpret which package version is the 'latest'.
I'm very surprised to hear you say that you support VS2010. These are Roslyn analyzers we're talking about so how can they be expected to work on anything earlier than VS2015? I suppose if someone installs the Roslyn toolset and jimmy-rigs their older MSBuild projects to run the Roslyn compiler *and* wire up the custom analyzers than maybe it would work, but that's not a VS scenario--that's a command-line build scenario and as such seems less likely to be hurt by a possibly malfunctioning `Update-Package` command.

Now as to whether *any* version of the NuGet client properly supports this portion or version of semver, I haven't actually confirmed. I know it deviates in several ways from semver so this might be one of them. And I agree, if NuGet misbehaves we should stick to the alpha005 format you're already using. I'll ask the NuGet team and report back here.

**Comment by sharwell** [comment]
@AArnott The analyzers only run if you edit with VS 2015 or build using those tools. Consider the [OpenStack.NET](https://github.com/openstacknetsdk/openstack.net) project, where I added [custom code analysis](https://github.com/openstacknetsdk/openstack.net/pull/472) features to make daily work easier for users working with VS 2015. The analysis is also enabled in the automated build, but none of this impacts the ability for users to load this solution in Visual Studio 2010 through 2013 (2012+ recommended due to the test suite's use of async/await). However, since the analysis packages *are* listed in the **packages.config** files, the version numbers listed there have to work properly with versions of NuGet that are available/installed in these older environments.

**Comment by AArnott** [comment]
The NuGet team reports that modern clients still only support semver 1.0.0. So I'll close the issue.
