### ISSUE TITLE
SA1201 (ElementsMustAppearInTheCorrectOrder) exception for OperatorDeclaration

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#680]
Currently SA1201 throws an exception if it encounters a `SyntaxKind.OperatorDeclaration` which is out of order. The exception is a `KeyNotFoundException` at the location where the diagnostic is reported.

**Comment by pdelvo** [comment]
This happened because the SA1201 docs dont mention operators at all. I think the best solution for this would be giving operators a fixed location. I think inserting operators between methods and structs would be appropriate. So the new order would be

Fields
Constructors
Finalizers
Delegates
Events
Enums
Interfaces
Properties
Indexers
Methods
Operators
Structs
Classes

**Comment by Przemyslaw-W** [comment]
Original SC saw operators as public static methods and ordered them as
such. If you aim at high backcompat bar, then this behavior should be
preserved. In my personal opinion separate location for operators makes
more sense. And given that operator overloading is rather rare in the code,
breaking change in this particular case is not a big deal.

2015-04-23 8:58 GMT+02:00 Dennis Fischer <notifications@github.com>:

**Comment by sharwell** [comment]
We can give operators their own location and be closer to the original behavior by placing them between Indexers and Methods. Any reason not to do that?

**Comment by pdelvo** [comment]
Im okay with that.
