### ISSUE TITLE
SA1121 UseBuiltInTypeAlias: batch codefix introduces compile error

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#723]
SA1121 fires on this line:

```csharp
    dictionary[new Object()] = new Object();
```

When I select to fix all violations in project, it transforms this line to

```csharp
    dictionary[new object()] = new Object()] = new object();
```

Which is incorrect

**Comment by sharwell** [comment]
This is essentially a duplicate of #466.

**Comment by AArnott** [comment]
I agree the symptom looks similar. But as it is a different rule, how can it be a duplicate? Do the two rules share code in their fixers?

**Comment by sharwell** [comment]
I closed this because it will automatically be tracked by #466. If we decide to implement a workaround in this project, we'll have to apply it to *all* code fixes that use the batch fixer, otherwise we either ignore it in all cases or wait for Roslyn to either fix it or provide a better API for applying batch fixes.

**Comment by mavasani** [comment]
@AArnott @sharwell I got a local repro for this, I am investigating further..
