### ISSUE TITLE
SA1100 autofix should replace base with 'this'

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#763]
SA1100 tells me to not use `base` unless a local implementation exists. Its auto-fixer simply removes the `base.` prefix, which then produces an SA1101 violation (to prefix local calls with `this.`).

Can the SA1100 auto-fixer be fixed to replace `base.` with `this.` so that fixing it does not produce a new violation of another one of SA11xx's own rules?

**Comment by pdelvo** [comment]
Our code fix should do exactly that. It might be a visual studio code fix that is doing that.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/a8fa0ec3053c2433bcdb5c00236774e3dddd2ba2/StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1100CodeFixProvider.cs#L57-L65

**Comment by sharwell** [comment]
You are seeing a code fix for IDE0002 (a built-in diagnostic). Unfortunately, we cannot just disable this one like IDE0003 (#532) right now because it applies to other situations where it is helpful.

I'm going to assume this is caused by one of the following. Please reopen it if you believe this is incorrect.

1. The light bulb contained a fix for IDE0002 and SA1100, and you clicked the one for IDE0002. The one you want to click has the following label:

  > Replace 'base.' with 'this.'

1. You are using Visual Studio 2015 RC and experiencing issues where StyleCopAnalyzers code fixes are not being presented in the light bulb. We encountered this with CTP 5 and again with CTP 6; in each case updating StyleCopAnalyzers to use the correct version of Roslyn resolved the problem. See #712 for the ongoing work on this migration for the recent update.

**Comment by AArnott** [comment]
Yes, it appears you're correct.
