### ISSUE TITLE
Implement analyzers for StyleCop+ rules (SPxxxx)

### ISSUE THREAD

**Issue by maboivin** [DotNetAnalyzers/StyleCopAnalyzers#782]
It would be nice if you could add analyzers for StyleCop+ rules (SPxxxx). You can find the source code here on github: https://github.com/shuruev/StyleCopPlus.

**Comment by sharwell** [comment]
It will be difficult to implement these rules as described on the StyleCopPlus page, because Roslyn analyzers are not easily configured.

Each of these rules would need to be submitted as a new rule proposal, and then discussed to determine if we want to add it. Note that some of the rules have already been proposed, and one of them even has a pull request with an implementation under review. As of right now, I believe the status is as follows:

* SP2000 (CodeLineMustNotEndWithWhitespace): #729 
* SP2001 (CheckAllowedIndentationCharacters): #33, #730
* SP2002 (CheckWhetherLastCodeLineIsEmpty): No proposal
* SP2100 (CodeLineMustNotBeLongerThan): No proposal
* SP2101 (MethodMustNotContainMoreLinesThan): No proposal
* SP2102 (PropertyMustNotContainMoreLinesThan): No proposal
* SP2103 (FileMustNotContainMoreLinesThan): No proposal

I'm marking this as a closed question regarding the proposal process. Please feel free to comment on existing issues or submit new proposals if there are any of these you particularly want to see included.

**Comment by hickford** [comment]
Thanks for the clarification. We also use StyleCop+ `StyleCopPlus.dll` http://stylecopplus.codeplex.com/  I'm not sure which rules though

**Comment by bmenees** [comment]
For anyone else looking for StyleCop+ rules, I missed them enough that I wrote analyzer equivalents for several of them in my new [Menees.Analyzers] (http://www.menees.com/Analyzers.htm) assembly.  It has rules similar to SP2001 (require tabs), SP2100 (long lines), SP2101 (long methods), SP2102 (long properties), and SP2103 (long files).

**Comment by DavidArno** [comment]
@bmenees, what was your reason for creating a separate analyser to StyleCopAnalyzers, rather than including them here?

@sharwell, your position on StyleCop+ seems a little unclear. For me at least (and I'm sure many others), StyleCop+ transformed StyleCop and it's vital that all its rules be implemented to make StyleCopAnalyzers a viable replacement tool. Here you seem to suggest that we can propose those rules. Elsewhere (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/422#issuecomment-128703160) you state that StyleCop+ rules won't be implemented, even if they are proposed. Also I'm puzzled by the idea that proposed rules like this need to be approved. Are you saying that if, for example, I implement SP2103 (files must not be more than n lines long) and submit a pull request, then it could be rejected simply because you or other existing contributors don't like it?

**Comment by sharwell** [comment]
> your position on StyleCop+ seems a little unclear

The only rules "grandfathered in" to this project are the ones that existed in StyleCop "classic" at the time this project was started. All other rules, regardless of origin, need to be proposed and then accepted before an implementation will be merged in. While we don't have an official documented procedure for accepting new rules, I can say that to date, no rules have been accepted that had an active objection from any code contributor to this project. In addition, rules which clearly worked well with another existing rule (e.g. #653 clearly works well with other rules regarding the order of using directives) needed at least two :+1: votes, and rules which represented new styles (e.g. #1451) tended to take three.

> Elsewhere (#422 (comment)) you state that StyleCop+ rules won't be implemented, even if they are proposed.

A more accurate statement is the rules would be unlikely to be accepted. Multiple contributors to this project have expressed interest in avoiding rules that do not have clear benefits under a fixed configuration. We already permanently disabled 5 StyleCop "classic" rules for this reason (#1057).

> Are you saying that if, for example, I implement SP2103 (files must not be more than n lines long) and submit a pull request, then it could be rejected simply because you or other existing contributors don't like it?

This is correct. And it's already happened for at least three of my own proposals which included fully-tested, working implementations along with code fixes. But the beauty of Roslyn is you can always create an analyzer that implements just SP2103 and use it along with StyleCop.Analyzers for a complete solution that works for you. :smile:

**Comment by bmenees** [comment]
I created my own set of rules because I know how to write them, and I know exactly what I want them to do.  Some of them conflict with existing StyleCop.Analyzers rules, and they're all coded in a different style (e.g., using tabs and using #regions).  I like my rules the way I write them, and I didn't want to have to debate them with others.

The beauty of analyzers and rulesets is that it's not an all or nothing proposition with an analyzer library.  I'm currently using 100% of the Menees.Analyzers rules, 80% of the StyleCop.Analyzers rules, and about 70% of the Code-Cracker rules.

**Comment by a1n1** [comment]
@bmenees is it possible to use your Menees.Analyzers in dotnet core projects?

**Comment by bmenees** [comment]
Probably not.  I don't use .NET Core at this point, and there's one place where I used Registry access in Menees.Analyzers to look up a setting.  So that required a reference to the .NET Framework.

**Comment by a1n1** [comment]
ok, got it, thanks for feedback. Just wondering why file max length and method max length still not implemented here. Because they are rather important one. So at least pull request for these rules should be acceptable.
