### ISSUE TITLE
SA1028 code fix fails to fix all AssemblyInfo.cs

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#886]
Repro: Create a new (console) project, all the analyzer reference. SA1028 is reported for a few places in the AssemblyInfo.cs file. The violations can be auto fixed one at a time, but when trying to fix all nothing will happen. No preview window will open.

**Comment by sharwell** [comment]
Note that the code fix does work on any single item in the file, which means this file will pass our current test suite (which applies fixes one at a time). Only the batch fixer fails.

I have a suspicion that this was fixed by dotnet/roslyn#2286, but we won't know for sure until we can test this with a post-RC release.

**Comment by paulomorgado** [comment]
I'm getting this on the comments and the fix only works one instance at a time. The batch fix doesn't even work for document,

**Comment by paulomorgado** [comment]
And I'm getting the same for SA1518.

**Comment by sharwell** [comment]
@paulomorgado The batch fixer was coded to treat **AssemblyInfo.cs** as generated code and disables *all* batch fixing in it.
