### ISSUE TITLE
Bug in StandardTextDiagnosticBase.HandleDeclaration

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#936]
When feeding the fixed code generated by the `SA1642SA1643CodeFixProvider` to the `SA1642ConstructorSummaryDocumentationMustBeginWithStandardText` analyzer or the `SA1643DestructorSummaryDocumentationMustBeginWithStandardText` analyzer, a diagnostic is generated. This should obviously not happen.

**Comment by vweijsters** [comment]
`HandleDeclaration` assumes that summary content always consists of 3 parts in a predefined order. This is too rigid, as the code fix produces (valid) summary content with 5 parts.

**Comment by sharwell** [comment]
Since Roslyn itself won't actually ever send the code fix a tree in the "bad" form shown here *and* we addressed the concerns in #935 by making the unit tests match Roslyn's behavior, I'm going to close this as **wontfix**. In theory the code could be made "more robust", but in practice it just doesn't matter because the current implementation already works.
